### ISSUE TITLE
Open SAML v3 

### ISSUE THREAD

**Issue by harish-myaccount** [spring-projects/spring-security-saml#148]
Quoting from
https://wiki.shibboleth.net/confluence/display/OpenSAML/Home

As of July 31, 2016, all security maintenance for the OpenSAML V2 Java release branch will cease
Are there any plans to use open SA/ML 3.x dependency?

**Comment by kristofferpeterhansel** [comment]
Issue #140 is sort of heading in that direction too. But looking at OpenSAML it is very hard to actually find v3 artifacts. And it seems to be in a fairly strange state where they only really doing work on the IdP side (since that is what they use it for themselves)

**Comment by donnchadh** [comment]
OpenSAML 3.x artifacts are available at https://build.shibboleth.net/nexus/content/repositories/releases/org/opensaml/opensaml-core/ .

**Comment by kristofferpeterhansel** [comment]
Yeah. But not propagated to Maven Central and there is even less documentation that for OpenSAML2. So I guess it is quite a bit of work to do this transition.

**Comment by donnchadh** [comment]
While 3.2.0 doesn't appear to be on maven central, it looks like 3.1.1 is: http://repo1.maven.apache.org/maven2/org/opensaml/opensaml-core/3.1.1/

**Comment by kristofferpeterhansel** [comment]
Ah right. I only tried the latest release. So I guess that was why it didn't resolve

**Comment by ibaskine** [comment]
Guys, why did you close this issue? OpenSaml 2 doesn't work with latest versions of BouncyCastle, which creates problems with both integrating the Spring SAML Extension with applications and passing security scans.

**Comment by gstanchev** [comment]
Perhaps because of #140 ?
