### ISSUE TITLE
How to Unit Test SAML security?

### ISSUE THREAD

**Issue by DenEwout** [spring-projects/spring-security-saml#201]
Hi,

Are there any guidelines as to how to test an application secured with SAML security?

Kind regards,

Ewout.

**Comment by vschafer** [comment]
Testing the whole SSO flow would require an active IDP, which would lead to a rather complex integration test requiring e.g. integration of Shibboleth (as an IDP).

For unit testing - e.g. with statically captured data sent from IDP - see unit tests of Spring SAML itself at https://github.com/spring-projects/spring-security-saml/tree/master/core/src/test/java/org/springframework/security/saml
