### ISSUE TITLE
NullPointerException when checking binding support

### ISSUE THREAD

**Issue by dinhani** [spring-projects/spring-security-saml#205]
If the request contentType is not set, it will throw a NullPointerException on line 45.

I had this issue when testing a request using CURL.

https://github.com/spring-projects/spring-security-saml/blob/10fdc14bbc4bb9c2516cf6e8f71000b2243016c7/core/src/main/java/org/springframework/security/saml/processor/HTTPPAOS11Binding.java#L44-L46

**Comment by fhanik** [comment]
Will not fix. Workaround exists. Pull requests contributions welcome to the [1.0.x branch](https://github.com/spring-projects/spring-security-saml/tree/history/1.0.x).
