### ISSUE TITLE
Spring SAML sample application doesn't show IDP's after changing web app address

### ISSUE THREAD

**Issue by dsu** [spring-projects/spring-security-saml#208]
It's not probably the application bug, but I have not Idea what could be the problem.
[stackoverflow](https://stackoverflow.com/questions/46003732/spring-saml-sample-application-doesnt-show-idps-after-changing-web-app-address)

**Comment by vschafer** [comment]
The issue seems to be related to Tomcat configuration. The sample application uses only simple JSPs with JSTL. I'm afraid there's no bug or issue in Spring SAML I could identify and help fix.
