### ISSUE TITLE
Compatibility with Axis 2 webservice

### ISSUE THREAD

**Issue by pokeMeNow** [spring-projects/spring-security-saml#209]
Spring Security SAML authentication not working, if AXIS 2 servlets are enabled in web.xml
 Working fine if AXIS2 servlets are disabled.

web.xml
	<servlet>
		<servlet-name>AxisServlet</servlet-name>
		<servlet-class>org.apache.axis2.transport.http.AxisServlet</servlet-class>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>AxisServlet</servlet-name>
	    <url-pattern>/services/*</url-pattern>
	</servlet-mapping>

Error message
 java.lang.IllegalArgumentException: Manager with name 'MetadataKeyInfoGenerator' does not exist

Do I miss any setting?

**Comment by vschafer** [comment]
I'm unable to assess how exactly could Axis interfere with Spring Security. One possibility is that Axis internally initializes OpenSAML and overrides Spring SAML settings.

Providing a project which reproduces the issue would make it possible to debug and find the root cause.
