### ISSUE TITLE
How to run this project ?

### ISSUE THREAD

**Issue by JavaHelper** [spring-projects/spring-security-saml#214]
I never understand how this project works infact after successfully created the account shown in the below screen shot.

Why its not redirecting back ?

![image](https://user-images.githubusercontent.com/8208031/31048433-81b26d58-a63a-11e7-8606-26335f31edd4.png)

**Comment by vschafer** [comment]
In case you are trying to integrate your application (a SAML 2.0 Service Provider) with an Identity Provider, just follow steps in the quick start guide - https://docs.spring.io/autorepo/docs/spring-security-saml/1.0.x/reference/html/chapter-quick-start.html

To try out the federation with a pre-integrated test application go to https://saml-federation.appspot.com/ and login with your ssocircle.com account which you need to create beforehand.

Both cases above will lead to a situation when you get "redirected back".
