### ISSUE TITLE
ADFS reponse status with value "RequestDenied" is not handled

### ISSUE THREAD

**Issue by suhaibmustafa** [spring-projects/spring-security-saml#224]
Hi,
When ADFS is configured to deny user access based on users association to a group or allow user based on specific group as shown in the snapshot below

![grpaccesspolicy](https://user-images.githubusercontent.com/35805415/35391025-cfba74c4-01f6-11e8-9b9a-f12f370b6e16.png)

Sample Rule Language for deny access:
```
c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", Value =~ "^(?i)S-1-5-21-3803708168-3451115266-1419502680-1110$"]
 => issue(Type = "http://schemas.microsoft.com/authorization/claims/deny", Value = "DenyUsersWithClaim");

```
ADFS responds with request denied status if user is not authorized, sample response status is as shown below:

```
<samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder">
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:RequestDenied" /></samlp:StatusCode>
</samlp:Status>
```
For this response, SAML throws exception as below:

```
Response has invalid status code urn:oasis:names:tc:SAML:2.0:status:Responder, status message is null
	at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:113)
```
I have used the sample securityContext.xml provided with minor changes.
My guess is the issue is because of the below code block:

https://github.com/spring-projects/spring-security-saml/blob/10fdc14bbc4bb9c2516cf6e8f71000b2243016c7/core/src/main/java/org/springframework/security/saml/websso/WebSSOProfileConsumerImpl.java#L113

This part of the code throws exception for any status code other than success. Let me know if I am missing anything and if there is a way to handle this status code.

Thanks,
Syed

**Comment by GlennBoschmans** [comment]
I have the same issue when using Keycloak. So the issue seems to be independent of the identity provider.

**Comment by GlennBoschmans** [comment]
After some quick investigation, I don't think that this is an actual issue. If the response is invalid (anything different than status code Success) a SAMLException is thrown. 
However, you can set a AuthenticationFailureHandler in the SAMLProcessingFilter. That seems to be the way to handle this exception, and gives you the possibility to handle failed login attempts. Spring provides some basic implementations for the handler, so you can easily redirect or forward to a specific page.

**Comment by suhaibmustafa** [comment]
@GlennBoschmans Thanks for pointing out. I had configured the same but it was not working, i was always getting 405 method not allowed error on page 'saml/SSO'. Then after reading your comment i went back and checked again and realized useForward property of the handler was set to true. It started working as expected after removing that setting. 

Thanks.

**Comment by dellekappa** [comment]
I made a pull request to have a better handling over the returned status code
#418

**Comment by yellapusony229** [comment]
> Hi,
> When ADFS is configured to deny user access based on users association to a group or allow user based on specific group as shown in the snapshot below
> 
> ![grpaccesspolicy](https://user-images.githubusercontent.com/35805415/35391025-cfba74c4-01f6-11e8-9b9a-f12f370b6e16.png)
> 
> Sample Rule Language for deny access:
> 
> ```
> c:[Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/groupsid", Value =~ "^(?i)S-1-5-21-3803708168-3451115266-1419502680-1110$"]
>  => issue(Type = "http://schemas.microsoft.com/authorization/claims/deny", Value = "DenyUsersWithClaim");
> ```
> 
> ADFS responds with request denied status if user is not authorized, sample response status is as shown below:
> 
> ```
> <samlp:Status>
>     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Responder">
>     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:RequestDenied" /></samlp:StatusCode>
> </samlp:Status>
> ```
> 
> For this response, SAML throws exception as below:
> 
> ```
> Response has invalid status code urn:oasis:names:tc:SAML:2.0:status:Responder, status message is null
> 	at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:113)
> ```
> 
> I have used the sample securityContext.xml provided with minor changes.
> My guess is the issue is because of the below code block:
> 
> https://github.com/spring-projects/spring-security-saml/blob/10fdc14bbc4bb9c2516cf6e8f71000b2243016c7/core/src/main/java/org/springframework/security/saml/websso/WebSSOProfileConsumerImpl.java#L113
> 
> This part of the code throws exception for any status code other than success. Let me know if I am missing anything and if there is a way to handle this status code.
> 
> Thanks,
> Syed
--------------------------------------------------------------------------------------------------------------
Hi Syed,

I am implementing Spring Boot SAML with ADFS as Identity provider. Done all the configurations as per the below document:
https://docs.spring.io/spring-security-saml/docs/1.0.0.RELEASE/reference/html

But when I am testing, I could able to redirect to ADFS login, after providing required credentials I am getting the below exception :
<samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester"><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy" />.
But we tried all the possibilities in-order to keep both the NAME ID policy as same.

Can you please suggest where I am getting wrong.

Thanks In Advance,
Yallapu Soni.

**Comment by suhaibmustafa** [comment]
@dellekappa share screenshots of your settings(complete policy and rules) for better clarity.

**Comment by suhaibmustafa** [comment]
@yellapusony229 share screenshots of your settings(complete policy and rules) for better clarity.
