### ISSUE TITLE
Provide Library Support for IdP

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#231]

**Comment by gstanchev** [comment]
This sounds interesting. Any more info?

**Comment by gstanchev** [comment]
This helps, yes. As an active user of this project I can only +1 Pivotal's return to support this project which seemed quite dead for a while. I saw several products at my ${work} head to pac4j and other alternatives because of this perseption. Also as someone who has architected and lead IdP dev effort this issue intrigues me. So thanks for the work on this...

**Comment by mor-anshuman** [comment]
I have never contributed to community but always wanted to do so, and very much interested in this to become a reality.

**Comment by fhanik** [comment]
Creating IDP code could be as simple as back porting the IDP implementation from the UAA that is built on Spring Security SAML 1.0

https://github.com/cloudfoundry/uaa/tree/a0504deb76d4ac928da8d0a8d26c8368f2bc60f8/server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp

You are welcome to take a stab at it and provide a pull reuest. This implementation is pretty basic, it takes the SAML SP implementation, and just makes the minor adjustments to make it an IDP.

It uses the `/saml/idp/**` URL path space for all the communication

**Comment by goeh** [comment]
I would love to help with testing and feedback on this. We brought in WSO2 for SAML IdP support in our Spring Cloud project but we are not happy with it.

**Comment by fhanik** [comment]
IDP Support is currently in the project and will be improved/maintained.

https://github.com/spring-projects/spring-security-saml/blob/7899d7436bd9324bc74085782d4ebb6466da6ffa/samples/boot/simple-identity-provider/src/main/java/sample/SimpleIdentityProviderApplication.java#L22
