### ISSUE TITLE
Support for Spring Security 5 and Spring Boot 2

### ISSUE THREAD

**Issue by zampettim** [spring-projects/spring-security-saml#236]
Update the library to support the version of Spring Security that ships with Spring Boot 2, Spring Security 5.

**Comment by tryge** [comment]
I use it with Spring Security 5 and Spring Boot 2, so far, I have one issue with ssl connections but I worked around that by loading metadata from the filesystem, otherwise it seems to work fine.

Is there anything else I should be aware of?

**Comment by zvrablik** [comment]
not related to spring security 5, but by default the SP initiated login uses SHA1 to sign the request sent from SP. I have created pull request to use sha256 by default, but not merged yet.

**Comment by fhanik** [comment]
Currently supported in 2.0.0 mile stone releases. Will be supported in 2.0.0

https://github.com/spring-projects/spring-security-saml

**Comment by fhanik** [comment]
@zvrablik hi Zdenek,
256 will be the new default. And configurable.
https://github.com/spring-projects/spring-security-saml/blob/3218b2baf4d8a6c10dc027eaaafb7805d3b6a4d2/core/src/main/java/org/springframework/security/saml/provider/config/LocalProviderConfiguration.java#L41-L42
