### ISSUE TITLE
1.0.4 release is still shown as a snapshot

### ISSUE THREAD

**Issue by lrozenblyum** [spring-projects/spring-security-saml#242]
SCENARIO:
See the webpage: https://projects.spring.io/spring-security-saml/

EXPECTED:
1.0.4 release is mentioned as a stable current release

ACTUALLY:
It's still marked as SNAPSHOT

![image](https://user-images.githubusercontent.com/1285898/39863613-d606e9c4-544f-11e8-9573-04cf0a68611b.png)

**Comment by csyperski** [comment]
What version is stable now, I see 1.0.3 on the spring site, on maven central I'm seeing 1.0.5.RELEASE?

**Comment by fhanik** [comment]
@csyperski Thank's for the report. No new development is happening. 1.0.5 is the latest (dependency update). Pages have been updated.
