### ISSUE TITLE
SP sample outside "develop" branch?

### ISSUE THREAD

**Issue by forgo** [spring-projects/spring-security-saml#243]
I'm trying to implement a service provider using the `samples` directory from your `develop` branch.

The sample seems to work well. Unfortunately, if I take it out of the context of your GitHub project and use the 1.0.4.RELEASE dependency, there are certain classes missing that were used in your sample.

So I am unable to resolve items such as:

- org.springframework.security.saml.config.SamlConfiguration
- org.springframework.security.saml.config.ExternalProviderConfiguration
- org.springframework.security.saml.config.SamlConfiguration
- org.springframework.security.saml.init.Defaults
- org.springframework.security.saml.init.SpringSecuritySaml
- etc...

When will these features be available in an official release? Do you have similar examples that do not rely on these classes? The documentation seems to be a little outdated.

**Comment by fhanik** [comment]
`develop` branch contains new code for our 2.x branch. This is a new codebase so documentation has not been updated yet. And it will not work with the old library. 

Monitor our blog or twitter feed for updates on releases.

**Comment by gstanchev** [comment]
Perhaps i missed it somewhere obvious but do you mind posting the twitter handle and the blog URL?

**Comment by fhanik** [comment]
https://spring.io/blog

I am aiming for a release in september.
