### ISSUE TITLE
SpringSecuritySaml appears to be opensaml specific

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#247]
Global initialization is not really spring like as it means you cannot dependency inject as easily. Rather than having a global init method on APIs, I think initialization of OpenSAML makes sense on implementation specific code.

**Comment by fhanik** [comment]
Fixed. Initialization happens as part of bean creation and can be overridden 

https://github.com/spring-projects/spring-security-saml/blob/93541271103c26b2d675e5fc4fad0ba6a4bf82b6/core/src/main/java/org/springframework/security/saml/provider/config/AbstractSamlServerBeanConfiguration.java#L59-L62

**Comment by rwinch** [comment]
@fhanik Could we make this an initializing Bean?

**Comment by fhanik** [comment]
We could, with no benefit but more risk. That could cause timing problems during other beans when they run `afterPropertiesSet` and they need the implementation to be fully initialized. For example, a server starting up that needs to parse SAML metadata during start up. The implementation needs to be fully initialized as soon as the bean is created.
