### ISSUE TITLE
Sample of 1.0.4.RELEASE is not functional

### ISSUE THREAD

**Issue by lrozenblyum** [spring-projects/spring-security-saml#254]
SCENARIO:
Load the sample webapp from 1.0.4.RELEASE

Try to load the metadata
(log-in as admin/admin)

EXPECTED:
No problems (as it worked in 1.0.3.RELEASE)

ACTUALLY:
The request was rejected because the URL contained a potentially malicious String ";"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:140)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:120)

**Comment by gstanchev** [comment]
Can you provide the metadata that is causing the issue?

**Comment by lrozenblyum** [comment]
It's a clean sample application checked out from 1.0.4.RELEASE

(I'm trying to log-in via admin/admin to get the SP metadata)

**Comment by lrozenblyum** [comment]
Maybe the problem is also reported here: https://stackoverflow.com/questions/50210084/how-to-resolve-firewall-requestrejectedexception-in-saml
