### ISSUE TITLE
Add single logout support

### ISSUE THREAD

**Issue by mraible** [spring-projects/spring-security-saml#257]
When I wrote about Spring Boot and SAML last year, I received lots of questions about how to logout.

https://developer.okta.com/blog/2017/03/16/spring-boot-saml

Please ensure that this library has logout functionality.

**Comment by fhanik** [comment]
Will do!
I will leave this open until completed.

**Comment by vschafer** [comment]
Hi Matt, it's a nice article, thank you for using Spring SAML.

The current version of Spring SAML 1.x supports both local logout and global logout, with the exception of SOAP binding.

In case it's still relevant, you can find details in the manual https://docs.spring.io/autorepo/docs/spring-security-saml/1.0.x/reference/htmlsingle/#configuration-logout
