### ISSUE TITLE
EntitiesDescriptor not supported by metadata parsing

### ISSUE THREAD

**Issue by aet2505** [spring-projects/spring-security-saml#258]
Hi,

I'm encountering the below error when attempting to configure this against my IDP

java.lang.IllegalArgumentException: not yet implemented class parsing:class org.opensaml.saml.saml2.metadata.impl.EntitiesDescriptorImpl
	at org.springframework.security.saml.spi.opensaml.OpenSamlImplementation.resolve(OpenSamlImplementation.java:332)

Looking at history of the project it seemed to be supported through MetadataManager in version 1.0.2.RELEASE of the project, although doesn't seem to be supported in the new OpenSamlImplementation. 

Am I doing something incorrectly, was this functionality deliberately removed or is this a regression?

Many Thanks
Adam

**Comment by fhanik** [comment]
Fixed via: https://github.com/spring-projects/spring-security-saml/commit/eb027144aea1337e304dd46cb8042676c6616e9f#diff-a481c4ff9d487e34f678e78342133e31

**Comment by aet2505** [comment]
Amazing Thanks!
