### ISSUE TITLE
Add support for DSAwithSHA256

### ISSUE THREAD

**Issue by ymartin59** [spring-projects/spring-security-saml#259]
Hello

We would like to be able to configure Service Provider with algorithm DSAwithSHA256, as it is now default algorithm when generating a Java keystore.

According to my findings, that algorithm is now supported in Apache XML Security - so it may be possible to enable it in org.opensaml.xml.signature.SignatureConstants (algo is commented out)

We request guidance how to add (by our own) this algorithm support in Spring Security SAML to deliver a work-around as a quick-fix.
Thank you in advance for your help
Yves

**Comment by fhanik** [comment]
You can override the [bean](https://github.com/spring-projects/spring-security-saml/blob/d3faddb21526a1dccbe9adcdd879a95620049d61/core/src/main/java/org/springframework/security/saml/provider/config/AbstractSamlServerBeanConfiguration.java#L59-L62)

or by calling the `[setSamlKeyStoreProvider()](https://github.com/spring-projects/spring-security-saml/blob/0d2c03d6c04fe95a450f2eb6dc1922cbcac48d02/core/src/main/java/org/springframework/security/saml/spi/opensaml/OpenSamlImplementation.java#L236) method
