### ISSUE TITLE
Rename "spi.Defaults" class to something else to avoid name conflict ?

### ISSUE THREAD

**Issue by gtiwari333** [spring-projects/spring-security-saml#270]
I was working on upgrading the codebase to use Spring SAML api v2 and got a bean name conflict between

`org.springframework.security.saml.spi.Defaults`
and
`springfox.documentation.spi.service.contexts.Defaults`

I fixed it in my project by overriding spi.AbstractProviderConfiguration#defaults() method to give an alias to "Defaults" bean as follows:

```
    @Bean("samlDefaults") 
    @Override
    public Defaults defaults() {
        return new Defaults(time());
    }

```

My question is can we rename this class to make sth like SAMLDefaults to avoid such conflict?

--

Btw, 

The v2 of spring-security-saml is really awesome. Its very easy to understand, configure and use than v1. Looking forward for the GA!!

**Comment by fhanik** [comment]
absolutely. will be done shortly

**Comment by fhanik** [comment]
Fixed via: https://github.com/spring-projects/spring-security-saml/commit/ba7cb26e9dc71d6b6143fe85ba73f314e610255d
