### ISSUE TITLE
How to encrypt assertion

### ISSUE THREAD

**Issue by Jacky0312** [spring-projects/spring-security-saml#272]
How to encrypt the assertion in SAMLResponse?
My SP metadata:
<?xml version="1.0" encoding="UTF-8"?>
            <md:EntityDescriptor ID="eeb6dbe9-0bb2-4cfd-9445-33c1dc88271d" entityID="spring.security.saml.sp.id" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
            	<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            		<ds:SignedInfo>
            			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            			<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
            			<ds:Reference URI="#eeb6dbe9-0bb2-4cfd-9445-33c1dc88271d">
            				<ds:Transforms>
            					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            				</ds:Transforms>
            				<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            				<ds:DigestValue>GcfJk45yptCjOsdR3d/tyPgO6cI=</ds:DigestValue>
            			</ds:Reference>
            		</ds:SignedInfo>
            		<ds:SignatureValue>
            OtKu0TgxhSKEyWEmQrR8hc1bJD4ZkTyydJfZQ1RpqrGCi6Qiqa8JPkeHB3NlWVewzoclV0aTX1yR
            vkzdBKWtPWHO50WJBX9BmhkoHK2G/nJSik0cvl3Dt2JuvidjUxNVCxWDVE70XUXHHfbJlw0rebQs
            gU+399aq8MJLctdShEg=
            		</ds:SignatureValue>
            		<ds:KeyInfo>
            			<ds:X509Data>
            				<ds:X509Certificate>MIICgTCCAeoCCQCuVzyqFgMSyDANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMCVVMxEzARBgNV
            BAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNlY3Vy
            aXR5IFNBTUwxCzAJBgNVBAsMAnNwMSAwHgYDVQQDDBdzcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDAe
            Fw0xODA1MTQxNDMwNDRaFw0yODA1MTExNDMwNDRaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
            V2FzaGluZ3RvbjESMBAGA1UEBwwJVmFuY291dmVyMR0wGwYDVQQKDBRTcHJpbmcgU2VjdXJpdHkg
            U0FNTDELMAkGA1UECwwCc3AxIDAeBgNVBAMMF3NwLnNwcmluZy5zZWN1cml0eS5zYW1sMIGfMA0G
            CSqGSIb3DQEBAQUAA4GNADCBiQKBgQDRu7/EI0BlNzMEBFVAcbx+lLosvzIWU+01dGTY8gBdhMQN
            YKZ92lMceo2CuVJ66cUURPym3i7nGGzoSnAxAre+0YIM+U0razrWtAUE735bkcqELZkOTZLelaoO
            ztmWqRbe5OuEmpewH7cx+kNgcVjdctOGy3Q6x+I4qakY/9qhBQIDAQABMA0GCSqGSIb3DQEBCwUA
            A4GBAAeViTvHOyQopWEiXOfI2Z9eukwrSknDwq/zscR0YxwwqDBMt/QdAODfSwAfnciiYLkmEjlo
            zWRtOeN+qK7UFgP1bRl5qksrYX5S0z2iGJh0GvonLUt3e20Ssfl5tTEDDnAEUMLfBkyaxEHDRZ/n
            bTJ7VTeZOSyRoVn5XHhpuJ0B</ds:X509Certificate>
            			</ds:X509Data>
            		</ds:KeyInfo>
            	</ds:Signature>
            	<md:SPSSODescriptor AuthnRequestsSigned="true" ID="243ee147-0bc3-49f6-81ab-4f359adc6567" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
            		<md:Extensions/>
            		<md:KeyDescriptor use="encryption">
            			<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            				<ds:X509Data>
            					<ds:X509Certificate>MIICgTCCAeoCCQCuVzyqFgMSyDANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMCVVMxEzARBgNV
            BAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNlY3Vy
            aXR5IFNBTUwxCzAJBgNVBAsMAnNwMSAwHgYDVQQDDBdzcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDAe
            Fw0xODA1MTQxNDMwNDRaFw0yODA1MTExNDMwNDRaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
            V2FzaGluZ3RvbjESMBAGA1UEBwwJVmFuY291dmVyMR0wGwYDVQQKDBRTcHJpbmcgU2VjdXJpdHkg
            U0FNTDELMAkGA1UECwwCc3AxIDAeBgNVBAMMF3NwLnNwcmluZy5zZWN1cml0eS5zYW1sMIGfMA0G
            CSqGSIb3DQEBAQUAA4GNADCBiQKBgQDRu7/EI0BlNzMEBFVAcbx+lLosvzIWU+01dGTY8gBdhMQN
            YKZ92lMceo2CuVJ66cUURPym3i7nGGzoSnAxAre+0YIM+U0razrWtAUE735bkcqELZkOTZLelaoO
            ztmWqRbe5OuEmpewH7cx+kNgcVjdctOGy3Q6x+I4qakY/9qhBQIDAQABMA0GCSqGSIb3DQEBCwUA
            A4GBAAeViTvHOyQopWEiXOfI2Z9eukwrSknDwq/zscR0YxwwqDBMt/QdAODfSwAfnciiYLkmEjlo
            zWRtOeN+qK7UFgP1bRl5qksrYX5S0z2iGJh0GvonLUt3e20Ssfl5tTEDDnAEUMLfBkyaxEHDRZ/n
            bTJ7VTeZOSyRoVn5XHhpuJ0B</ds:X509Certificate>
            				</ds:X509Data>
            			</ds:KeyInfo>
            		</md:KeyDescriptor>
            		<md:KeyDescriptor use="signing">
            			<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            				<ds:X509Data>
            					<ds:X509Certificate>MIICgTCCAeoCCQCQqf5mvKPOpzANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMCVVMxEzARBgNV
            BAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNlY3Vy
            aXR5IFNBTUwxCzAJBgNVBAsMAnNwMSAwHgYDVQQDDBdzcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDAe
            Fw0xODA1MTQxNDQ0NDZaFw0yODA1MTExNDQ0NDZaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
            V2FzaGluZ3RvbjESMBAGA1UEBwwJVmFuY291dmVyMR0wGwYDVQQKDBRTcHJpbmcgU2VjdXJpdHkg
            U0FNTDELMAkGA1UECwwCc3AxIDAeBgNVBAMMF3NwLnNwcmluZy5zZWN1cml0eS5zYW1sMIGfMA0G
            CSqGSIb3DQEBAQUAA4GNADCBiQKBgQCXJXpaDE6QmY9eN9pwcG8k/54aK9YLzRgln64hZ6mvdK+O
            IIBB5E2Pgenfc3Pi8pF0B9dGUbbNK8+8L6HcZRT/3aXMWlJsENJdMS13pnmSFimsTqoxYnayc2Ea
            HULtvhMvLKf7UPRwX4jzxLanc6R4IcULJZ/dg9gBT5KDlm164wIDAQABMA0GCSqGSIb3DQEBCwUA
            A4GBAHDyh2B4AZ1C9LSigis+sAiVJIzODsnKg8pIWGI7bcFUK+i/Vj7qlx09ZD/GbrQts87Yp4aq
            +5OqVqb5n6bS8DWB8jHCoHC5HACSBb3J7x/mC0PBsKXA9A8NSFzScErvfD/ACjWg3DJEghxnlqAV
            Tm/DQX/t8kNTdrLdlzsYTuE0</ds:X509Certificate>
            				</ds:X509Data>
            			</ds:KeyInfo>
            		</md:KeyDescriptor>
            		<md:KeyDescriptor use="signing">
            			<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            				<ds:X509Data>
            					<ds:X509Certificate>MIICgTCCAeoCCQC3dvhia5XvzjANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMCVVMxEzARBgNV
            BAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNlY3Vy
            aXR5IFNBTUwxCzAJBgNVBAsMAnNwMSAwHgYDVQQDDBdzcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDAe
            Fw0xODA1MTQxNDQ1MzBaFw0yODA1MTExNDQ1MzBaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
            V2FzaGluZ3RvbjESMBAGA1UEBwwJVmFuY291dmVyMR0wGwYDVQQKDBRTcHJpbmcgU2VjdXJpdHkg
            U0FNTDELMAkGA1UECwwCc3AxIDAeBgNVBAMMF3NwLnNwcmluZy5zZWN1cml0eS5zYW1sMIGfMA0G
            CSqGSIb3DQEBAQUAA4GNADCBiQKBgQC2iAUrJXrHaSOWrU95v8GUGVVl5vWrYrNRFtsK5qkhB/nR
            bL08CbqIeD4pkJuIg0LuJdsBuMtYqOnhQSFF5tT36OIdld9SfPA5m8zqPLsCcjWPQ66xoMdReEXN
            9E8s/mZOXn3jkKIqywUxJ+wkS5qoBlvmShwDff+igFlF/fBfpwIDAQABMA0GCSqGSIb3DQEBCwUA
            A4GBACDBjvIpc1/2yZ3TQe29bKif5pr/3NdKz4MWBJ6vjRk7Bs2hbPrM2ajxLbqPx6PRPeTOw5XZ
            grufDj9HmrvKHM2LZTp/cIUpxcNpVRyDA4iVNDc7V3qszaWP9ZIswAYnvmyDL2UHVDLE8xoGz/Ak
            xsRNN9VXNHewjQO605umiAKJ</ds:X509Certificate>
            				</ds:X509Data>
            			</ds:KeyInfo>
            		</md:KeyDescriptor>
            		<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8080/sample-sp/saml/sp/logout"/>
            		<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>
            		<md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
            		<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8080/sample-sp/saml/sp/SSO" index="0" isDefault="true"/>
            		<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8080/sample-sp/saml/sp/SSO" index="1" isDefault="false"/>
            		<md:AttributeConsumingService index="0" isDefault="true"/>
            	</md:SPSSODescriptor>
            </md:EntityDescriptor>

SAMLResponse:
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response Destination="http://localhost:8080/sample-sp/saml/sp/SSO" ID="4e9dba6f-fa1a-42ee-9c50-86a04e17de10" InResponseTo="7e2badc4-793a-42b9-9147-a4e83084a87d" IssueInstant="2018-07-25T13:49:30.249Z" Version="2.0" xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
	<saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">spring.security.saml.idp.id</saml2:Issuer>
	<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
		<ds:SignedInfo>
			<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
			<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
			<ds:Reference URI="#4e9dba6f-fa1a-42ee-9c50-86a04e17de10">
				<ds:Transforms>
					<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
					<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				</ds:Transforms>
				<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
				<ds:DigestValue>uFAX3zFLH8tZ7GeEaMTdErD9woQ=</ds:DigestValue>
			</ds:Reference>
		</ds:SignedInfo>
		<ds:SignatureValue>
dRC16VbNp5o0jNYC2UPUIj9sF9+vhQJLuIFjaX3ivNyU/1ns8TYDOVJ5sWIsGkYkCUAgT13GNoRG
pXl51j45mgEj1aEiF53sCkwpdZqf++g7TftW7ZWvb6aJq05RWQ3w8GzLoynS0SrrKXaOqEcr1QGd
kbWQ6TYBBLSnF4aHuuo=
		</ds:SignatureValue>
		<ds:KeyInfo>
			<ds:X509Data>
				<ds:X509Certificate>MIIChTCCAe4CCQDo0wjPUK8sMDANBgkqhkiG9w0BAQsFADCBhjELMAkGA1UEBhMCVVMxEzARBgNV
BAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNlY3Vy
aXR5IFNBTUwxDDAKBgNVBAsMA2lkcDEhMB8GA1UEAwwYaWRwLnNwcmluZy5zZWN1cml0eS5zYW1s
MB4XDTE4MDUxNDE0NTUyMVoXDTI4MDUxMTE0NTUyMVowgYYxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
DApXYXNoaW5ndG9uMRIwEAYDVQQHDAlWYW5jb3V2ZXIxHTAbBgNVBAoMFFNwcmluZyBTZWN1cml0
eSBTQU1MMQwwCgYDVQQLDANpZHAxITAfBgNVBAMMGGlkcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDCB
nzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA2EuygAucRBWtYifgEH/ErVUive4dZdqo72Bze4Mb
kPuTKLrMCLB6IXxt1p5lu+tr0JxOiRO3KFVOO3D0l+j9zOow4g+JdoMQsjSzA6HtL/D9ZjXP6iUx
FCYx+qmnVl3X9ipBD/HVKOBlzIqeXTSa5D17uxPQVxK64UDOI3CyY4cCAwEAATANBgkqhkiG9w0B
AQsFAAOBgQAj+6b6dlA6SitTfz44LdnFSW9mYaeimwPP8ZtU7/3EJCzLd5eq7N/0kYPNVclZvB45
I0UMT77AHWrNyScm56MTcEpSuHhJHAqRAgJKbciCTNsFI928EqiWSmu//w0ASBN3bVa8nv8/rafu
utCq3RskTkHVZnbT5Xa6ITEZxSncow==</ds:X509Certificate>
			</ds:X509Data>
		</ds:KeyInfo>
	</ds:Signature>
	<saml2p:Status>
		<saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
	</saml2p:Status>
	<saml2:Assertion ID="345e402c-07ad-467b-bc2c-b270b337dcfa" IssueInstant="2018-07-25T13:49:30.234Z" Version="2.0" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
		<saml2:Issuer>spring.security.saml.idp.id</saml2:Issuer>
		<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
				<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
				<ds:Reference URI="#345e402c-07ad-467b-bc2c-b270b337dcfa">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
					</ds:Transforms>
					<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
					<ds:DigestValue>bU7hZuX5Ea2v7TMamC2eX5B7oM4=</ds:DigestValue>
				</ds:Reference>
			</ds:SignedInfo>
			<ds:SignatureValue>
odUKfzigExj+N3fYG6kXIygnEj0hhvHu0eZwjjn7HCWzB+u0nvMbn0LwD+WFRnevDnqAU15p3HGT
TTMUNWrzqOthHiitX9Sh4iEG4fg1m41FEaRAjeJOE5epCkZy2E9HtJZ9pNPVpgRoh7p6dzs1oRv2
2+NODRnA+6+VZUD2zNI=
			</ds:SignatureValue>
			<ds:KeyInfo>
				<ds:X509Data>
					<ds:X509Certificate>MIIChTCCAe4CCQDo0wjPUK8sMDANBgkqhkiG9w0BAQsFADCBhjELMAkGA1UEBhMCVVMxEzARBgNV
BAgMCldhc2hpbmd0b24xEjAQBgNVBAcMCVZhbmNvdXZlcjEdMBsGA1UECgwUU3ByaW5nIFNlY3Vy
aXR5IFNBTUwxDDAKBgNVBAsMA2lkcDEhMB8GA1UEAwwYaWRwLnNwcmluZy5zZWN1cml0eS5zYW1s
MB4XDTE4MDUxNDE0NTUyMVoXDTI4MDUxMTE0NTUyMVowgYYxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
DApXYXNoaW5ndG9uMRIwEAYDVQQHDAlWYW5jb3V2ZXIxHTAbBgNVBAoMFFNwcmluZyBTZWN1cml0
eSBTQU1MMQwwCgYDVQQLDANpZHAxITAfBgNVBAMMGGlkcC5zcHJpbmcuc2VjdXJpdHkuc2FtbDCB
nzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA2EuygAucRBWtYifgEH/ErVUive4dZdqo72Bze4Mb
kPuTKLrMCLB6IXxt1p5lu+tr0JxOiRO3KFVOO3D0l+j9zOow4g+JdoMQsjSzA6HtL/D9ZjXP6iUx
FCYx+qmnVl3X9ipBD/HVKOBlzIqeXTSa5D17uxPQVxK64UDOI3CyY4cCAwEAATANBgkqhkiG9w0B
AQsFAAOBgQAj+6b6dlA6SitTfz44LdnFSW9mYaeimwPP8ZtU7/3EJCzLd5eq7N/0kYPNVclZvB45
I0UMT77AHWrNyScm56MTcEpSuHhJHAqRAgJKbciCTNsFI928EqiWSmu//w0ASBN3bVa8nv8/rafu
utCq3RskTkHVZnbT5Xa6ITEZxSncow==</ds:X509Certificate>
				</ds:X509Data>
			</ds:KeyInfo>
		</ds:Signature>
		<saml2:Subject>
			<saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" SPNameQualifier="spring.security.saml.sp.id">TSRI3301</saml2:NameID>
			<saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
				<saml2:SubjectConfirmationData InResponseTo="7e2badc4-793a-42b9-9147-a4e83084a87d" NotOnOrAfter="2018-07-25T13:51:30.234Z" Recipient="http://localhost:8080/sample-sp/saml/sp/SSO"/>
			</saml2:SubjectConfirmation>
		</saml2:Subject>
		<saml2:Conditions NotBefore="2018-07-25T13:48:30.234Z" NotOnOrAfter="2018-07-25T13:51:30.234Z">
			<saml2:AudienceRestriction>
				<saml2:Audience>spring.security.saml.sp.id</saml2:Audience>
			</saml2:AudienceRestriction>
		</saml2:Conditions>
		<saml2:AuthnStatement AuthnInstant="2018-07-25T13:49:30.234Z" SessionIndex="bda5d522-c6ef-48ac-8d63-75b43837c29a" SessionNotOnOrAfter="2018-07-25T14:19:30.234Z">
			<saml2:AuthnContext>
				<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
			</saml2:AuthnContext>
		</saml2:AuthnStatement>
		<saml2:AttributeStatement/>
	</saml2:Assertion>
</saml2p:Response>

**Comment by fhanik** [comment]
hi @Jacky0312 
Encryption is not yet supported. Decryption is. Contributions welcome. In lieu of that, I will keep this issue open to remind us to implement encryption.

**Comment by fhanik** [comment]
@Jacky0312 
I implemented this today, please review the configuration setting to enable it.

https://github.com/spring-projects/spring-security-saml/blob/48e33312f57006383e3da4aeef95c5ad6cc53f7a/samples/boot/simple-identity-provider/src/main/resources/application.yml#L30-L32

**Comment by davidjayb** [comment]
@fhanik I am configuring the extension programmatically, is there a configuration bean I can use to set this property?

**Comment by fhanik** [comment]
There are two places you can do it. 

Very high up, the [samlIdentityProviderProvisioning](https://github.com/spring-projects/spring-security-saml/blob/d3faddb21526a1dccbe9adcdd879a95620049d61/core/src/main/java/org/springframework/security/saml/provider/identity/config/SamlIdentityProviderServerBeanConfiguration.java#L44-L53) bean

Or replace the [configuration repository](https://github.com/spring-projects/spring-security-saml/blob/d3faddb21526a1dccbe9adcdd879a95620049d61/core/src/main/java/org/springframework/security/saml/provider/config/AbstractSamlServerBeanConfiguration.java#L89-L93) bean
