### ISSUE TITLE
Remove Network in favor of RestOperations

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#274]
Handling network communications is not a simple endeavor. There are many features that `Network` does not cover (pooling connections, credentials, etc). Rather than creating our own client (i.e. Network) we should use an instance of `RestOperations`.

**Comment by rwinch** [comment]
Is there a reason we need Network? User's can customize by configuring custom timeouts on the RestTempalte they are using

**Comment by fhanik** [comment]
Network.java is an internal utility class for creating the correct request factory with the anticipated validation just to avoid code duplication.
