### ISSUE TITLE
Make StringUtils Private

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#275]
StringUtils is only used in DefaultSamlMessageHandler. Make it private

**Comment by msamm-r7** [comment]
i've branched of rb2.0.0.BUILD to do this (can't do it off master as per Contrib guidelines). is that going to be ok?

**Comment by fhanik** [comment]
@msamm-r7 I'm doing a refactor right now to simplify the APIs. There will be one more update to develop before the APIs stabilize
