### ISSUE TITLE
Difference between two projects

### ISSUE THREAD

**Issue by karanb192** [spring-projects/spring-security-saml#279]
How is this project any different from 
https://github.com/spring-projects/spring-security-saml-dsl

In my project, it doesn't matter which dependency I add from the two. My project works fine in both cases. Could you please elaborate the difference?

**Comment by fhanik** [comment]
The `dsl` project aims to implement a Java configuration solution of the `core(this)` library.

For example: [DSL](https://github.com/spring-projects/spring-security-saml-dsl/blob/master/samples/spring-security-saml-dsl-sample/src/main/java/com/example/SecurityConfiguration.java#L27-L40)

```
		.serviceProvider()
			.keyStore()
				.storeFilePath("saml/keystore.jks")
				.password("secret")
				.keyname("spring")
				.keyPassword("secret")
				.and()
			.protocol("https")
			.hostname("localhost:8443")
			.basePath("/")
			.and()
		.identityProvider()
			.metadataFilePath(metadataUrl)
			.and();
```

While this project is the actual implementation of the SAML Specifications (Service Provider and Identity Provider)
