### ISSUE TITLE
Split up into core, SP, and IDP related jars

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#280]
We should split up the code into core, SP, and IDP related jars.

**Comment by fhanik** [comment]
@rwinch 

Would like your opinion because such a large portion of the code is core.
From a development perspective it means more work creating two additional gradle modules, but very little benefit for managing such a small set of classes in those modules.

What is the benefit that you imagine will rise out of this?

```
core - 104 classes
idp - 11 classes
sp - 15 classes
```

**Comment by rwinch** [comment]
Let's hold off on this for now, but the fact that so much is core seems to be a sign that something else may be wrong. At minimum our jar should not be called spring-security-saml2-core as it is today. Perhaps we can switch that part now

**Comment by fhanik** [comment]
switch it to?

**Comment by rwinch** [comment]
Perhaps just spring-security-saml2

**Comment by fhanik** [comment]
I've adjusted it so that it is just a continuation of 1.0.x. Only the version changes during an upgrade.

**Comment by rwinch** [comment]
It appears the jar that is produces is still spring-security-saml-core. We should either split this up or rename the jar to spring-security-saml2.

**Comment by fhanik** [comment]
Jars split up in [MVP Branch](https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp)

```
./service-provider/build/libs/spring-security-saml2-service-provider-3.0.0.BUILD-SNAPSHOT.jar
./core/build/libs/spring-security-saml2-core-3.0.0.BUILD-SNAPSHOT.jar
./transform/keycloak/build/libs/spring-security-saml2-transform-keycloak-3.0.0.BUILD-SNAPSHOT.jar
./transform/opensaml/build/libs/spring-security-saml2-transform-opensaml-3.0.0.BUILD-SNAPSHOT.jar
./boot-config/build/libs/spring-security-saml2-boot-config-3.0.0.BUILD-SNAPSHOT.jar
```
