### ISSUE TITLE
YML setting problems

### ISSUE THREAD

**Issue by whyuan1976** [spring-projects/spring-security-saml#282]
My project is Java Maven Project which use Spring Boot 1.5.4.
After I copy the resource from simple service provider sample code, project can't start.

When load application.yml, it failed.

```
Caused by: java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148) ~[na:1.8.0_65]

```
I think the error is loading List setting.

Something like :         
```
       name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified 

        //LocalProviderConfiguration 
	private List<NameId> nameIds = emptyList();
```

emptyList can't use add function, it throws error.
Is it ok?

**Comment by fhanik** [comment]
hi @whyuan1976 Are you able to change the code to use `new LinkedList<>()` to confirm that is the case with Spring Boot 1.5?

I'd be happy to make that change if that is it.

**Comment by fhanik** [comment]
Please reopen if that doesn't fix the issue.
