### ISSUE TITLE
Webflux Support

### ISSUE THREAD

**Issue by rameezrajas** [spring-projects/spring-security-saml#293]
Spring security has webflux support. But I donot see a webflux support for the spring-security-saml project. Do we have any plan to support webflux in near future?

**Comment by fhanik** [comment]
@rameezrajas Nothing is planned or in the works. Is there something specific you're looking for?

**Comment by rameezrajas** [comment]
We use spring cloudgateway for routing to backend services and trying to secure the spring cloudgateway using SAML security. Spring cloudgateway is purely based on reactive webflux. We are having hard time implementing SAML security, since spring-saml-security project is yet to support webflux.
Only approach for us now is to rewrite all servlet filters to WebFilters. 
Do you know any other easy way of implementing SAML security in spring cloudgateway?

**Comment by fhanik** [comment]
@rameezrajas 
Makes sense. 
I would probably slate that for a 2.1.x release of this library because it changes the requirement on Spring Security to 5.0.x+

I will leave this issue open. There is nothing coming in the short term (this month), but we'll have time to consider it after that.

If you do end up implementing it before I do, contributions are much appreciated

**Comment by KyleChamberlin** [comment]
Will the 2.1 or 3.x versions ever be released GA? what is the roadmap like to this?

**Comment by fhanik** [comment]
@KyleChamberlin the 3.x will get webflux support and will go GA. It's in development. It's slow, so I don't have any timelines for you.

2.x will not go GA. We continue to accepts PR for this branch and will publish milestone releases until 3.x goes GA

**Comment by KyleChamberlin** [comment]
Is there a targetted Spring boot or Spring framework version for the 3.x line to align with? Just trying to get a feel for the alignment here. 

Also, as an aside, the company I work for has a lot riding on Spring Security and we would love to contribute where we can to helping this transition along the way, what major work is outstanding for the 3.x line and how is it best for me or my fellow developers to coordinate that work?

**Comment by jzheaux** [comment]
Further development of Spring Security's support for SAML has moved to Spring Security proper.

To that end, I've added [the equivalent issue](https://github.com/spring-projects/spring-security/issues/8619) in Spring Security and am closing this one here.
