### ISSUE TITLE
Configuration metadata is not automatically generated by spring-boot-configuration-processor

### ISSUE THREAD

**Issue by scalony2002** [spring-projects/spring-security-saml#294]
I am binding configuration properties to SamlServerConfiguration as shown below

```
@ConfigurationProperties(prefix = "spring.security.saml2")
@Configuration
public class AppConfig extends SamlServerConfiguration {
}
```

This approach sort of works but unfortunately I am not getting contextual help from IDE when editing `application.properties` or `application.yaml`. I think the problem is that the configuration class SamlServerConfiguration  does not have annotate its nested properties with @NestedConfigurationProperty.  Can you make the library more user friendly by adding support for configuration processor?

**Comment by fhanik** [comment]
@scalony2002 You are more familiar with this than I am. Would you be able to submit a PR to demonstrate? It doesn't have to be complete, but at least a starting point.

**Comment by scalony2002** [comment]
OK I will do it.

**Comment by scalony2002** [comment]
Here is the pull request, please review

https://github.com/spring-projects/spring-security-saml/pull/306

**Comment by fhanik** [comment]
Will be superseded by the [MVP](https://github.com/spring-projects/spring-security-saml/tree/262ecfcc45a0775cfc01591646b226895f8ea38f/boot-config/src/main/java/org/springframework/security/saml/boot/configuration)
