### ISSUE TITLE
SamlServiceProviderSecurityDsl should align with other configurers

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-saml#295]
Let's try and make this configurer look and feel like other configurers where possible.

I'd recommend taking a look at [`OAuth2LoginConfigurer`](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2LoginConfigurer.java) or [`OAuth2ClientConfigurer`](https://github.com/spring-projects/spring-security/blob/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/oauth2/client/OAuth2ClientConfigurer.java) as ones where I would expect there to be some distinct similarities.

Here are a couple of spots where I see some deviation:

* `configure` has a specific meaning in the `Configurer` API, and it actually isn't intended for external use, even though it is `public`. In hindsight, making that method `public` has caused some confusion over the years, so let's not propagate it by adding other `public` "configure" methods, even if we feel like they have semantic alignment with the original from the API.
* There are lots of little configuration endpoints in this configurer which will be cumbersome to maintain over time. It also makes the DSL a bit anemic in that the functional use case is not communicated through the API. Would recommend that the DSL focus on domain objects instead of POJOs.

**Comment by jzheaux** [comment]
The pattern for individual property-type configuration is more typically via a Spring Boot property where then Spring Boot will correctly create and expose a bean that your configurer picks up. There are certainly cases where something is so common that we will promote the individual property up to first-class in the DSL, but it's usually more maintainable to not begin with a DSL property per configuration property.

**Comment by fhanik** [comment]
I believe this has been addressed in the [coarse grained configurer](https://github.com/spring-projects/spring-security-saml/blob/ce308f4ddbb2ee1b6206a4bee050e23eb3cac163/service-provider/src/main/java/org/springframework/security/config/annotation/web/configurers/SamlServiceProviderConfigurer.java#L30)
