### ISSUE TITLE
SamlResponseAuthenticationFilter should focus on http-specific logic

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-saml#296]
Spring Security filters will more typically focus on extracting information from the request into an `Authentication` object and then send that off to an `AuthenticationManager`.

The existing filter does delegate to an Authentication Manager, which is good. In addition, though, after extracting the assertion from the request, it also hydrates and validates it, things which do not require the HTTP context to perform correctly.

Would recommend instead something like a "SamlAuthenticationToken" which has the serialized response data and then an Authentication Provider that performs the hydration and validation.

It might be helpful to take a look at the [`JwtAuthenticationProvider`](https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/authentication/JwtAuthenticationToken.java) in Spring Security which does the hydration and validation of a serialized JWT token.

And more broadly, the hope is that folks familiar with other Spring Security "core" libraries like OAuth2 will look at the SAML library and see a lot of natural cognates.

**Comment by fhanik** [comment]
@jzheaux I'm trying to understand the alignment differences that you mention.

For example, the difference between [OAuth2LoginAuthenticationFilter](https://github.com/spring-projects/spring-security/blob/d46f83caf4c13b59ec49031fec57db2560ab5049/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilter.java#L151-L202) and [SAML WebSsoAuthenticationFilter](https://github.com/spring-projects/spring-security-saml/blob/92d97f1c01265ad08f74e292ccd305091f857e70/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/WebSsoAuthenticationFilter.java#L83-L122)

Both of them seem to be doing enough validation to be able to throw subclasses of `AuthenticationException` prior to delegating to the authentication manager.

What did you have in mind? What am I missing?

**Comment by fhanik** [comment]
Completed: https://github.com/spring-projects/spring-security-saml/blob/baff922892be48f6daf073c075a1a33260503057/service-provider/servlet/src/main/java/org/springframework/security/saml2/serviceprovider/servlet/filter/Saml2WebSsoAuthenticationFilter.java#L33-L66
