### ISSUE TITLE
Consider removing SimpleAuthenticationManager 

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-saml#297]
`SimpleAuthenticationManager` is so simple, I love it!

That said, `ProviderManager` seems plenty sufficient for the SAML use case, where instead you might introduce an Authentication Provider where the core authentication logic is performed.

**Comment by fhanik** [comment]
removed in MVP branch

https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
