### ISSUE TITLE
Consider moving configurations to using a Builder

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-saml#298]
A number of the configuration classes have deep copy support in order to ensure that they are not unexpectedly mutated outside of some trusted boundary.

Is it necessary for these classes to be altered after configuration time?

If not, then builders might remove the need for extra copies. A builder can allow for more sophisticated construction of a thereafter immutable object.

**Comment by fhanik** [comment]
Completed in: Superseded by https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
