### ISSUE TITLE
Remove the need for SamlServerConfiguration & SamlServiceProviderServerBeanConfiguration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#301]
This does not align with the Spring Security way of configuring things. Instead configuration should be done at the DSL level.

Related: #295

**Comment by fhanik** [comment]
Issue resolved via the [MVP](https://github.com/spring-projects/spring-security-saml/blob/a29409aed34c408c679679eafe423d52ff40d42f/samples/boot/starter-sp/src/main/java/sample/SecurityConfig.java#L52-L72)
