### ISSUE TITLE
Consider making SamlLogoutSuccessHandler package-private

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#302]
`SamlLogoutSuccessHandler` has a `package-private` constructor but the class is `public`.
We should consider making `SamlLogoutSuccessHandler` `package-private` as well.

I see that `SamlLogoutSuccessHandler.LogoutStatus` is being referenced outside of it's package, but maybe this can be extracted?

**Comment by fhanik** [comment]
Superseded by https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
