### ISSUE TITLE
Consider creating ServiceProviderRegistration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#303]
SAML based log in and OAuth2 Based login are quite similar. It would be nice to align our APIs to a large degree.

One such API that would be valuable is a ServiceProviderRegistration that aligns with Spring Security's [ClientRegistration](https://github.com/spring-projects/spring-security/blob/5.0.8.RELEASE/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistration.java#L35). There would also be something like a [ClientRegistrationRepository](https://github.com/spring-projects/spring-security/blob/5.0.8.RELEASE/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrationRepository.java) to look up the registrations.

We would likely have a `Filter` that requests a SAML response similar to [OAuth2AuthorizationRequestRedirectFilter](https://github.com/spring-projects/spring-security/blob/5.1.0.RELEASE/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilter.java)

When the response comes back the SAMLResponse will be validated by an `AbstractAuthenticationProcessingFilter` similar to [OAuth2LoginAuthenticationFilter](https://github.com/spring-projects/spring-security/blob/5.1.0.RELEASE/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2LoginAuthenticationFilter.java)

**Comment by fhanik** [comment]
Component called [ServiceProviderResolver](https://github.com/spring-projects/spring-security-saml/blob/develop-3.0/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/ServiceProviderResolver.java#L24) and for multi tenancy reasons builds on the Servlet Spec.
Reactive will have a similar component. 

This prevents the need to use thread locals when multi tenancy is an after thought.
