### ISSUE TITLE
Consider Removing ThreadLocalSamlConfigurationRepository

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-saml#304]
`SamlConfigurationRepository` appears to be an interface for retrieving server configurations from a cache, a database, from in-memory, etc.

It has an in-memory implementation called `StaticSamlConfigurationRepository`. And one might imagine application developers creating a DB-centric implementation that maps to their database representations.

I don't think that the ThreadLocal implementation of this interface is necessary. Spring already comes with a great caching utility and so do other common open source products like Hibernate, making repeated queries for the same data very fast. These also ship with configurable cache expiration semantics. So, this class doesn't solve anything that I couldn't just solve with a tool that was built for that.

Caching is also tricky to get right and there are two cache expiration policies at play here, one in a filter that is resetting the thread local and the other internal to this class. And since there is a public setter on this object, it could get even more interesting as already cached items could have their expiration changed after they were cached.

That being the case, I'd recommend that this library focus on what it is great at and not try and cache this configuration for the user.

**Comment by fhanik** [comment]
Removed. Leveraging ServletRequest.getAttribute/setAttribute instead

Superseded by https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
