### ISSUE TITLE
Configuring SAML security in sample simple-service-provider

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#305]
The `simple-service-provider` sample configures SAML security as follows:

```java
@EnableWebSecurity
public class SecurityConfiguration {

	@Configuration
	@Order(1)
	public static class SamlSecurity extends SamlServiceProviderSecurityConfiguration {

		private AppConfig appConfig;

		public SamlSecurity(BeanConfig beanConfig, @Qualifier("appConfig") AppConfig appConfig) {
			super("/saml/sp/", beanConfig);
			this.appConfig = appConfig;
		}

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			super.configure(http);
			http.apply(serviceProvider())
				.configure(appConfig);
		}
	}

	@Configuration
	public static class AppSecurity extends WebSecurityConfigurerAdapter {
             ....
}
```

Looking at an alternative approach for configuring SAML, we can do this:

```java
@EnableWebSecurity
public class SecurityConfiguration {

	@Configuration
	@Order(1)
	@Import(SamlServiceProviderSecurityConfiguration.class)
	public static class SamlSecurity extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			SamlServiceProviderSecurityDsl configurer = serviceProvider();
			configurer
					.entityId("entity-id")
					.prefix("prefix")
					.singleLogout(true)
					....

			http.apply(configurer);
		}
	}

	@Configuration
	public static class AppSecurity extends WebSecurityConfigurerAdapter {
             ....
}
```

The key points are:

- Instead of `SamlSecurity` extending `SamlServiceProviderSecurityConfiguration`, it extends `WebSecurityConfigurerAdapter` which is more typical and common from what a user would do.
- `SamlServiceProviderSecurityConfiguration` would be `@Import` or conditionally imported using `ImportSelector`. This again is common - the use of defining `@Configuration` classes that initialize the underlying infrastructure components.
- In the `configure(HttpSecurity http)` method, the user would configure the various options for SAML Security using the DSL.

**Comment by angolosB3rat1** [comment]
How we redirect to IDP login page, every time I am redirected to the select Provider IDP page

**Comment by fhanik** [comment]
Superseded by https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
