### ISSUE TITLE
Consider removing SamlFilter to simplify the Filter hierarchy

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#307]
There are a few `Filter`'s that extend from `SamlFilter` - which serves the main purpose of holding members for the most part and a default template method `processHtml` for html response processing.

I think `SamlFilter` can be removed to simplify the `Filter` hierarchy and the `Filter` sub-classes can be composed with the required members via constructor instantiation.

The `processHtml` can be implemented using  a delegation-based strategy or simply `doFilterInternal`.

**Comment by fhanik** [comment]
Superseded by https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
