### ISSUE TITLE
Provide SAMLUserDetailsService for v2

### ISSUE THREAD

**Issue by davidkron** [spring-projects/spring-security-saml#309]
I'm currently trying to migrate our applications to the new spring-security-saml implementation (using the milestone releases) so that I will be prepared when the first release version is published.

One feature from the previous version of the library that we are extensively using in our applications is the `SAMLUserDetailsService`. Unfortunately, I did not find something similar in v2 to migrate to.

It would be great to have a similar "hook" in v2 to provide custom user details from the application.

**Comment by fhanik** [comment]
Cross referencing this issue here: https://github.com/spring-projects/spring-security-saml/issues/297

**Comment by stunaz** [comment]
@fhanik care to show how, please?

**Comment by fhanik** [comment]
In the upcoming [`branch`](https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp). You can do something like:

```
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			//application security
			.authorizeRequests()
				.anyRequest().authenticated()
				.and()
			//saml security
			.apply(
				saml2Login()
					.authenticationManager(myCustomAuthManager);
			)
		;
	}
```

If you want Single Logout to work properly, ensure that the `Authentication` object returned implements [`SamlAuthentication`](https://github.com/spring-projects/spring-security-saml/blob/555f0a2590b7ad84a1ebd9398ec9e8efe495069c/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/authentication/SamlAuthentication.java#L27)
