### ISSUE TITLE
ClassCast when IDP metadata has both IDPSSODescriptor and SPSSODescriptor

### ISSUE THREAD

**Issue by przem** [spring-projects/spring-security-saml#311]
I'm setting up my service as a SP to work with remote IDP. 
The IDP has a metadata definition containing both IDPSSODescriptor and SPSSODescriptor, this causes that SelectIdentityProviderFilter throws ClassCastException from doFilterInternal method.

The origin of the problem is in OpenSamlImplementation#getMetadata that returns Metadata instead of expected IdentityProviderMetadata due to fact that ssoProviders has a list of 2 elements (sp and idp)

**Comment by fhanik** [comment]
@przem Would it be possible for you to attach your metadata here?

**Comment by fhanik** [comment]
@przem in the meantime, the work around is to take out the SPSSODescriptor element. You can configure the metadata as XML in your config.

**Comment by przem** [comment]
> @przem Would it be possible for you to attach your metadata here?

Looks moreless like this:
[testportal-sso-metadata.xml.zip](https://github.com/spring-projects/spring-security-saml/files/2384067/testportal-sso-metadata.xml.zip)

**Comment by przem** [comment]
> @przem in the meantime, the work around is to take out the SPSSODescriptor element. You can configure the metadata as XML in your config.

Yes, i've done it this way, so the workaround works
