### ISSUE TITLE
Add New IDp provider configuration at RunTime

### ISSUE THREAD

**Issue by tejasgarde** [spring-projects/spring-security-saml#312]
We are integrating spring-security-saml extension to support SSO in our spring boot microservice.
our application should allow different customers to add their IDP metadata and their certificate to  microserice (which is an SP) so that microserice can initiate SSO against their idp

Right now we are defining metadata and extendedmetadata using CachingMetadataManager. But this happens only once at Startup of the application 

we are not able to figure out how do we add a new idp metadata to MetadataManager at runtime and also load new key in .jks file with reloading of keyManager bean.

What is the standard Practice to Configure multiple IDp at Runtime , Does Spring Security SAML Support this?

**Comment by fhanik** [comment]
In **Spring Security SAML 1.0.x**

_This is doable, but it is not easy. You can see how the Cloud Foundry [UAA did it](https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/NonSnarlMetadataManager.java)_


In **Spring Security SAML 2.0.x (develop branch)**

This will be part of the library itself via the [SamlConfigurationRepository](https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/provider/config/SamlConfigurationRepository.java)

The idea here is to support dynamic configuration and multi tenant systems out of the box.

it's recommend to use a [filter to read configuration](https://github.com/spring-projects/spring-security-saml/blob/bb3b145d0c366d790ea08d8a31ed5cc4a0969b16/core/src/main/java/org/springframework/security/saml/provider/config/ThreadLocalSamlConfigurationFilter.java#L27-L45) prior to initiating a request

and you can see how the [UAA does it](https://github.com/cloudfoundry/uaa/blob/feature/spring_saml_v2_poc/server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/saml/SamlProviderConfigurationProvisioning.java)

**Comment by deepd** [comment]
Is there an ETA on the 2.x release?

**Comment by fhanik** [comment]
hi @deepd 

There will not be a 2.0 release. The core code development continues in the Spring Security project

https://github.com/spring-projects/spring-security-saml#current-status
