### ISSUE TITLE
Milestone release are not in repository M12 -M17

### ISSUE THREAD

**Issue by gtiwari333** [spring-projects/spring-security-saml#313]
I tried to use the new milestone repository in my test project and maven couldn't find it in the milestone repository:

https://repo.spring.io/milestone/org/springframework/security/extensions/spring-security-saml-core/

The last change pushed to repo was from M11 on Sept 1.

Would you mind publishing the new changes to repo?

**Comment by cyrillzadra** [comment]
Seem to be in a different repo -> http://repo.spring.io/list/milestone/org/springframework/security/extensions/spring-security-saml2/

**Comment by fhanik** [comment]
Same repo, different artifact name. This one aligns with the 1.0.x release train so that there is no change in artifactId or groupId when upgrading.
