### ISSUE TITLE
walk around or good approach instead of SAMLAuthenticationProvider after 2.0.0?

### ISSUE THREAD

**Issue by jihlee** [spring-projects/spring-security-saml#315]
Hello guys.

I'm considering to add SAML authentication to my Authorization server which uses Spring Security 5.
I saw that SAMLAuthenticationProvider is removed from 2.0.0 Milestones releases. 

Is there any walk around or best practice to use Spring security SAML with AuthenticationProvider interface?

Thank you!

**Comment by fhanik** [comment]
Hi @jihlee We will be adding a SAML authentication provider in 2.0.0 too. In the meantime, you can simply replace the AuthenticationManager bean

https://github.com/spring-projects/spring-security-saml/blob/412b3ca7a01e85a83fdf5ea1cb5f01e45533d89a/core/src/main/java/org/springframework/security/saml/provider/service/config/SamlServiceProviderServerBeanConfiguration.java#L65
