### ISSUE TITLE
MetatdataManager can not use Long.MAX_VALUE as RefreshCheckInterval

### ISSUE THREAD

**Issue by bthalmayr** [spring-projects/spring-security-saml#319]
Setting the RefreshCheckInterval as
`hostingMetadataManager.setRefreshCheckInterval(Long.MAX_VALUE)`

leads to Exception
`Caused by: java.lang.IllegalArgumentException: Illegal execution time.
	at java.util.Timer.sched(Timer.java:388)
	at java.util.Timer.schedule(Timer.java:248)
	at org.springframework.security.saml.metadata.MetadataManager.afterPropertiesSet(MetadataManager.java:137)`

Timer.java

`    public void schedule(TimerTask task, long delay, long period) {
        if (delay < 0)
            throw new IllegalArgumentException("Negative delay.");
        if (period <= 0)
            throw new IllegalArgumentException("Non-positive period.");
        sched(task, System.currentTimeMillis()+delay, -period);
    }`

MetadataManager.afterPropertiesSet ....

`...
            this.timer.schedule(new RefreshTask(), refreshCheckInterval, refreshCheckInterval);
        } else {
            log.debug("Metadata reload timer is not created, refreshCheckInternal is {}", refreshCheckInterval);
        }
        refreshMetadata();
    }`

**Comment by fhanik** [comment]
Will not fix, but will accept pull requests for the [1.0.x release](https://github.com/spring-projects/spring-security-saml/tree/history/1.0.x) branch
