### ISSUE TITLE
X509Utilities: certificates must not be parsed by the library

### ISSUE THREAD

**Issue by volkc-basf** [spring-projects/spring-security-saml#321]
There is no need to parse/cleanup the certificates here: 

https://github.com/spring-projects/spring-security-saml/blob/1e4d3f568c456b1f74e9f57198e4b94fe990bb9b/core/src/main/java/org/springframework/security/saml/util/X509Utilities.java#L60-L64

The `CertificateFactory` used to load the pem files is able to handle the ---- BEGIN/END CERTIFICATE ---- statements [very well](https://docs.oracle.com/javase/8/docs/api/java/security/cert/CertificateFactory.html#generateCertificate-java.io.InputStream-).

https://github.com/spring-projects/spring-security-saml/blob/1e4d3f568c456b1f74e9f57198e4b94fe990bb9b/core/src/main/java/org/springframework/security/saml/util/X509Utilities.java#L78

Best,
Chris

**Comment by fhanik** [comment]
@volkc-basf Thanks for your issue Christian.
I tried removing the getDER and tests started failing. 
Feel free to reopen this issue, or open a new PR.

I currently run the tests in the [`feature/spring_sec_5.2_saml_mvp`](https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp) branch
