### ISSUE TITLE
Admin Login Fails

### ISSUE THREAD

**Issue by jdolinski** [spring-projects/spring-security-saml#323]
Login to the metadata administration console fails:

**Console Log**
1. /saml/web/login at position 5 of 11 in additional filter chain; firing Filter: 'UsernamePasswordAuthenticationFilter'
2. Checking match of request : '/saml/web/login'; against '/saml/web/login'
3. Request is to process authentication
4. Authentication attempt using org.springframework.security.authentication.dao.DaoAuthenticationProvider
5. User '' not found
6. Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Bad credentials

The Spring Security 3 to 4 upgrade default attributes for j_username and j_password have changed.

- The form-login@username-parameter attribute default value changed from j_username to username. If an application explicitly provides the attribute, no action is required for the migration.

- The form-login@password-parameter attribute default value changed from j_password to password. If an application explicitly provides the attribute, no action is required for the migration.

**Comment by jdolinski** [comment]
Created pull request to use spring security default attribute names on form

**Comment by fhanik** [comment]
Fixed via https://github.com/spring-projects/spring-security-saml/commit/2cffabdcab7f5d669fb7fbd7e163a181d97f40a0
