### ISSUE TITLE
AuthnRequest always sent to first endpoint listed in IdP Metadata

### ISSUE THREAD

**Issue by cratermoon** [spring-projects/spring-security-saml#327]
Summary: In the sample SP, after choosing the IdP, the browser is always redirected to *first listed* endpoint from the IdP.

Steps to Reproduce:

- Set up the sample SP to point to an IdP that provides multiple `SingleSignOnService` bindings
- Make the first listed binding `Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"`
- Ensure the sample SP attempts to use the HTTP-Redirect method.
- Attempt to log in

Expected behavior:
Browser is directed to the IdP's login page

Actual behavior:
Error from the IdP

Additional details.
There's a mismatch between the endpoint used and the `AuthnRequest` values for `Destination` and `ProtocolBinding` 

From the IdP's metadata:
`        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" req-attr:supportsRequestedAttributes="true" Location="https://idp.example.com/idp/profile/SAML2/POST/SSO"/>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" req-attr:supportsRequestedAttributes="true" Location="https://idp.example.com/idp/profile/SAML2/Redirect/SSO"/>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign" req-attr:supportsRequestedAttributes="true" Location="https://idp.example.com/idp/profile/SAML2/POST-SimpleSign/SSO"/>`

HTTP Request
`GET https://idp.example.com/idp/profile/SAML2/Redirect/SSO?SAMLRequest=<elided> HTTP/1.1`

SAML
`<saml2p:AuthnRequest AssertionConsumerServiceURL="http://localhost:8080/sample-sp/saml/sp/SSO/alias/boot-sample-sp"
                     Destination="https://idp.example.com/idp/profile/SAML2/POST/SSO"
                     ForceAuthn="false"
                     ID="_dde7f77-e892-4791-bcd1-0ecedc6a9851"
                     IsPassive="false"
                     IssueInstant="2018-10-24T16:37:01.496Z"
                     ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                     Version="2.0"
                     xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                     >
 .
.
.
</saml2p:AuthnRequest>`

This could be because of line 129 in `core/src/main/java/org/springframework/security/saml/provider/service/HostedServiceProviderService.java` which reads
`setDestination(idp.getIdentityProvider().getSingleSignOnService().get(0));`

**Comment by fhanik** [comment]
Thank you Steven, I will review this ( @cratermoon )

**Comment by cratermoon** [comment]
I have a 1-liner fix for this now. Shall I submit a PR?

**Comment by fhanik** [comment]
That would be awesome. Against the develop branch please.
