### ISSUE TITLE
[Question] sp/select - Choose a default provider:

### ISSUE THREAD

**Issue by stunaz** [spring-projects/spring-security-saml#328]
Hi,
In my UseCase, I just have 1 provider. And I want my user not to see the "Select an Identity Provider".

Is there a way to have control over that page?

**Comment by fhanik** [comment]
My recommendation is to submit a PR with a configuration option.

The code is in: https://github.com/spring-projects/spring-security-saml/blob/f37f409afa4d7cc60dc94486d7587623e196b93b/core/src/main/java/org/springframework/security/saml/provider/service/SelectIdentityProviderFilter.java#L76

If you don't want to do that, just include a filter earlier in the chain that does the redirect
