### ISSUE TITLE
Need to verify metadata signature

### ISSUE THREAD

**Issue by eyalkaspi** [spring-projects/spring-security-saml#331]
Excuse me if it is not a problem, but while inspecting the source code on the (yet to be released) 2.0.0 version, I've discovered that the logic to verify the metadata signature is missing (or I misunderstand the code). 

I am referring to [this line of the code](https://github.com/spring-projects/spring-security-saml/blob/c5fe837/core/src/main/java/org/springframework/security/saml/provider/identity/HostedIdentityProviderService.java#L79) which passes `null` as `verificationKeys` and thus, if my understanding of the code is correct, will simply skip signature verification. 

Based on the [documentation for the 1.X, see chapter 7.2.4 ](https://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-metadata.html#configuration-metadata-idp-signature), signature verification was supported (by importing the CA into the application keystore).

Is my understanding that the feature is missing correct? If so, is there a plan to implement this before the final release of the 2.0.0 version?

**Comment by fhanik** [comment]
Your assessment is correct. And yes, we will add this feature. It requires a an addition to the static configuration by adding the verification keys at configuration time. I will keep this issue open.

**Comment by OrangeDog** [comment]
@fhanik is this available in [2.0.0.M24](https://mvnrepository.com/artifact/org.springframework.security.extensions/spring-security-saml2-core/2.0.0.M24).
Are there any issues with using that snaphot?
The [2.0.x release notes](https://docs.spring.io/spring-security-saml/docs/2.0.x/reference/html/chapter-whats-new.html) haven't been filled in.
When is a release with this feature expected?

**Comment by fhanik** [comment]
@OrangeDog 

The 2.0.x code base will never reach GA to avoid having two GA codebases with the same feature set. 

We're refactoring the core in the [`develop-3.0` branch](https://github.com/spring-projects/spring-security-saml/tree/develop-3.0) to make eventually merge into Spring Security ([core](https://github.com/spring-projects/spring-security)) and it will follow the main Spring Security release train.
