### ISSUE TITLE
Validate that Response is always signed

### ISSUE THREAD

**Issue by d8s** [spring-projects/spring-security-saml#333]
Is there a way to validate that a `Response` is always signed. The `LocalServiceProviderConfiguration.wantAssertionsSigned` when is `true` only checks that assertions are signed. 

There doesn't seem to be a way to force check that a `Response` is always signed.

**Comment by fhanik** [comment]
You can simply extend/override the existing [SamlValidator](https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/spi/DefaultValidator.java#L306-L308) and require that a signature is present.

There isn't a configuration option for the response itself. Not all providers sign at the response level.
