### ISSUE TITLE
Signed response doesn't satisfy wantAssertionSigned

### ISSUE THREAD

**Issue by eyalkaspi** [spring-projects/spring-security-saml#334]
This issue relates to https://github.com/spring-projects/spring-security-saml/issues/333.

Wit the current state of the develop branch, one can either set `wantAssertionsSigned` and see SAML responses being rejected if the response itself is signed but not the assertions, or unset `wantAssertionsSigned` and write our own SamlValidator.

I believe that many applications actually want to enforce that either the assertions or the response is signed (or both) which is not easy to achieve. This appears to be the behavior of the 1.X versions of this project (see https://jira.spring.io/browse/SES-120 and the corresponding [commit](https://github.com/spring-projects/spring-security-saml/commit/49ed98f60d077069563bcd5a60a757975d62da30)) and the expected behavior per the SAML 2.0 Spec, Section 5.3 Signature Inheritance.

So I would recommend either changing the behavior of `wantAssertionsSigned` to be consistent with the v1.X behavior and really mean "want assertion to be signed or to inherit signature", or adding another boolean/enum configuration option.

**Comment by fhanik** [comment]
@eyalkaspi Thank you for the report. I will work on this today.
I will align it with spec and 1.0.x release.

**Comment by fhanik** [comment]
@eyalkaspi Fixed. I will be pushing a M18 milestone release with this fix. It's an important one.
Thank you for your contribution!!

**Comment by eyalkaspi** [comment]
Thanks for the quick turnaround. I've verified that this fix actually solves the problem I was seeing.
