### ISSUE TITLE
Updating Sample to be Minimal Configuration

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#335]
The current sample applications are importing a `SamlBootConfiguration`, exposing a `ServiceProviderConfigurationResolver` bean, etc. I'd like to see an absolute minimum configuration for a user. I want to see a sample application that requires the least amount of setup for a user wanting to get going. Everything that can be defaulted should be.

In reference to the comment of ServiceProviderConfigurationResolver being exposed as a spybean...Keep in mind that a minimum sample application probably doesn't have many unit tests because all of the code exists outside of the application. Instead it might have some MockMvc style tests or integration tests, but I wouldn't expect much in the line of unit tests in there.

**Comment by rwinch** [comment]
Thanks for the updates @fhanik! I had some additional feedback, so I reopened this ticket to continue discussing. My feedback can be seen below:

* Is there a need for the [@Order](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L38)? I don't think this should be necessary for a minimal configuration.
* [@EnableOpenSaml](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L37) does not fit in with Spring Secury's conventions. There is only a single annotation and the rest of the features are only enabled through the DSL. The reason for this is because what does `@EnableOpenSaml` mean when there are multiple `WebSecurityConfigurerAdapter` instances?
* Is there a reason that [SamlTransformer](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L46) needs to be a Bean and injected in? Can it just be defaulted instead?
*[antMatcher("/**")](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L53)is the default and can be removed
* We shouldn't use `antMatchers` in a Spring MVC app (`mvcMatchers` is preferred). However, this can be further simplified to `anyRequest`
* Is [formLogin](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L57) necessary? I'd think we should be able to automatically redirect to the IdP by having the serviceProvider() set the AuthenticationEntryPoint without the need for formLogin being set (which implies username/password authentication is allowed).
* [logoutUrl("/logout")](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L60) is the default so it could be removed
* [logoutSuccessUrl](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L61) should not need to be configured by the user. Instead, the serviceProvider should be able to configure it automatically. I'd also like the URL to follow Spring Security conventions which would use something like /logout/saml which better mirrors /login/cas
* We should be able to default the [samlTransformer](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java#L66)

**Comment by fhanik** [comment]
@rwinch Excellent feedback. All valid points, that I agree with.

**Comment by fhanik** [comment]
Configuration [updated](https://github.com/spring-projects/spring-security-saml/blob/feature/spring_sec_5.2_saml_mvp/samples/boot/starter-sp/src/main/java/sample/MinimalSamlSecurityConfiguration.java?ts=3#L35-L53)

I'm considering the `alias` property name. Renaming ID may be confusing, because both SP and IDP metadata have a property named ID in it. I'm still pondering it.

**Comment by fhanik** [comment]
Closing. No feedback in 30+ days.
