### ISSUE TITLE
SamlResponseAuthenticationFilter valides signatures twice

### ISSUE THREAD

**Issue by eyalkaspi** [spring-projects/spring-security-saml#336]
`SamlResponseAuthenticationFilter#attemptAuthentication` works by first reading the XML from the response data into a response object and then validate the response object.

When deserializing the xml, the code is a little convoluted:

```
                 Saml2Object result = type.cast(getTransformer().fromXml(xml, null, decryptionKeys));
		//in order to add signatures, we need the verification keys from the remote provider
		RemoteMetadata remote = getRemoteProvider(result);
		List verificationKeys = remote.getSsoProviders().get(0).getKeys();
		//perform transformation with verification keys
		return type.cast(getTransformer().fromXml(xml, verificationKeys, decryptionKeys));
```

The xml is actually parsed twice, the second instance being required so that the response includes signatures. Indeed, `OpenSamlImplementation#resolveAssertion` only includes signatures if `verificationKeys` are defined (not null, not empty), and also actually validates signatures.

So in addition to parsing XML twice, one is validating them twice (once in `fromXml` and once in `AbstractHostedProviderService#validate).

I believe the root of the problem is that reading signatures and validating them has been implementing as a single unit in `OpenSamlImplementation`. As a matter of fact, the `Signature` objects have a `validated` property which is always true as either the objects get created in `validateSignature` and are flagged as `validated` or an exception is thrown.

If instead of validating signatures, the `resolve` functions simply read the signatures, there wouldn't be a need to parse the XML twice either.  Alternatively, parsing and validation of signatures could be kept together, but `AbstractHostedProviderService#validate` doesn't need to validate signatures again (as it appears that all callers of this method have the same problem). The `validated` flag of signatures could be removed and `SamlValidator#validateSignature` removed too (making it explicit that signature validation must occurs while parsing).

**Comment by fhanik** [comment]
@eyalkaspi I will review it. 

> making it explicit that signature validation must occurs while parsing

I'm thinking the opposite. When you have raw XML and wanting to parse that into an object, you don't know the remote party, thus you can't supply keys signature verification keys. 

So I believe we should probably remove signature validation from the parsing, and making validation an explicit separate operation.

What do you think?

**Comment by fhanik** [comment]
We're going to be moving forward with the [`MVP`](https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp) branch. 

In this branch, this does not take place.
