### ISSUE TITLE
HostedServiceProviderConfiguration.Builder.builder()

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#340]
I'm wondering if we need:

```java
builder()
builder(HostedServiceProviderConfiguration configuration)
```

Maybe we can make `withKeys(...)` `static` and return the `Builder` or maybe we add `withConfiguration(HostedServiceProviderConfiguration configuration)`?

**Comment by fhanik** [comment]
All of these have been fixed in the latest [branch](https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp/core/src/main/java/org/springframework/security/saml/registration)
