### ISSUE TITLE
HostedServiceProviderConfiguration constructor should be private

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#341]
The constructor for `HostedServiceProviderConfiguration` is quite large so I don't think we want to expose it given that it has a builder. I'm also thinking we should remove this constructor since the builder has access to setting the members.

`org.springframework.security.oauth2.client.registration.ClientRegistration` faces the same challenge of setting multiple attributes. Take a look at this for some common patterns.

**Comment by jgrandja** [comment]
The same applies to `ExternalIdentityProviderConfiguration`, `HostedIdentityProviderConfiguration`

**Comment by fhanik** [comment]
@jgrandja Thanks for the feedback.

On this one I disagree. In the use cases I consider, configuration should be easily be serialized/deserialized to and from JSON. 

Making the constructor private, and thereby the class non extensible, we limit this functionality and force developers to write custom transformers, thus failing them in limit the code the have to write.

Ideally, I would have made these serializable (via json) but that adds a dependency that can be problematic.

**Comment by fhanik** [comment]
Please reopen if I'm missing something

**Comment by jgrandja** [comment]
@fhanik 

> the use cases I consider, configuration should be easily be serialized/deserialized to and from JSON

Can you elaborate on the use cases? I'm just not aware of the use cases where you need to serialize/deserialize JSON.

> Making the constructor private

I wasn't implying making it private. I should have been more clear. Just a default constructor.

Also, even if we kept the large constructor, serializing/deserializing with JSON is not going to be easy either since you have to ensure the JSON attributes are correctly mapped to the constructor args. Making it a Java Bean with getters/setters would be the easiest but not sure if you want that either?

**Comment by fhanik** [comment]
hi @jgrandja 
In the UAA for example. Multi tenant system. One running service, hosts multiple IDPs and SPs.
All configuration is stored in JSON format. 

With a public constructor, you can override the constructor, and map using annotations to each field.

Making the constructor private, will make this impossible.

**Comment by fhanik** [comment]
Reopen if this wish to continue the discussion.

**Comment by jgrandja** [comment]
> Making the constructor private, will make this impossible.

I was not suggesting making it private as I already mentioned in this [comment](https://github.com/spring-projects/spring-security-saml/issues/341#issuecomment-444254358).

I just don't think a constructor with all those args is very useable. Having a default no-arg public constructor which JavaBean properties would make the JSON serialization/deserialization quite simple.

I still feel we should get rid of the "all-arg" constructor.

**Comment by fhanik** [comment]
aah I keep reading the title of the issue. Changing the definition of an issue through a comment becomes a bit harder to follow.

These classes is intentionally immutable. The immutable object is intentionally developed to be thread safe.

As the implementation, or an extension to the implementation, would be very difficult if these values could change once provided to a component.

There are two other ways to get regular mutable objects. One is using the builder, the other is using the [`boot-config` module](https://github.com/spring-projects/spring-security-saml/blob/a29409aed34c408c679679eafe423d52ff40d42f/boot-config/src/main/java/org/springframework/security/saml/boot/registration/LocalServiceProviderConfiguration.java#L24)

**Comment by fhanik** [comment]
Reference: https://github.com/spring-projects/spring-security-saml/issues/298
