### ISSUE TITLE
DefaultSamlAuthentication extends AbstractAuthenticationToken

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#345]
Is it possible to have `DefaultSamlAuthentication extends AbstractAuthenticationToken`? And to rename `DefaultSamlAuthentication` to `SamlAuthentication`?

Then we can remove `interface SamlAuthentication`

**Comment by fhanik** [comment]
There is a different use case here:

The application develop can provide an [`authenticationManager`](https://github.com/spring-projects/spring-security-saml/blob/70fe11aab4cb914432548ea6dbabf0de41dc9080/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlWebSsoAuthenticationFilter.java#L121) that gets invoked during authentication.

In some cases, definitely in the CF UAA, the authentication object will be replaced by a custom one.
If that custom authentication object implements `SamlAuthentication` then SAML single logout will still work.

The interface provides a purpose here. Please reopen if you disagree, and we can elaborate more.
