### ISSUE TITLE
No binding enum for urn:mace:shibboleth:2.0:profiles:AuthnRequest

### ISSUE THREAD

**Issue by shurupov** [spring-projects/spring-security-saml#346]
Shibboleth IDP metadata contains the following line
`<SingleSignOnService Binding="urn:mace:shibboleth:2.0:profiles:AuthnRequest" Location="https://shibbolethidp/idp/profile/SAML2/Unsolicited/SSO" />`
So [here](https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/saml2/metadata/Binding.java#L56) exception happens.
Seems the adding just one value to enum will not fix this. I suppose, we need to add hadler of it somewhere.

**Comment by shurupov** [comment]
Also issue with NameIDFormat urn:mace:shibboleth:1.0:nameIdentifier

from `<NameIDFormat>urn:mace:shibboleth:1.0:nameIdentifier</NameIDFormat>` in IDP metadata

**Comment by fhanik** [comment]
I will look into adding a `CUSTOM` identifier to handle cases like these

**Comment by shurupov** [comment]
@fhanik thank you

**Comment by shurupov** [comment]
Investigated. About NameIdFormat. Need to change [this line](https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/saml2/metadata/NameId.java#L64) to `return UNSPECIFIED;`
Little bi later I will create pull request about this and about binding. Maybe it will include some another fixes about supporting connection to Shibboleth IDP.
