### ISSUE TITLE
Tries to download invalid metadata multiple times causing slowness

### ISSUE THREAD

**Issue by gtiwari333** [spring-projects/spring-security-saml#349]
**Problem:**

When the IDP metadata URL instead of the whole metadata XML in configured, and a IDP site is down,  DefaultMetadataCache#getMetadata() tries to download the metadata upto 4 times and causes slowness when logging in using an IDP that's up and running. It will cause  problem when we have a ton of IDP configured in the system and couple of them are down at the moment.  See logs:
[spring-saml-cache.txt](https://github.com/spring-projects/spring-security-saml/files/2740866/spring-saml-cache.txt)

**How to reproduce:**

1. On the develop branch, run simple-identity-provider and simple-service-provider projects from samples/boot folder.

2. Note that: the samples\boot\simple-service-provider\src\main\resources\application.yml has 4 IDP metadata urls listed. Only two of them are up and running.

3. Add a breakpoint or line System.out.println("Not found in cache ............ " + uri); on org.springframework.security.saml.spi.DefaultMetadataCache#getMetadata() as shown below.

```
	public byte[] getMetadata(String uri, boolean skipSslValidation) {
		byte[] data = cache.get(uri);
		if (data == null) {
			System.out.println("Not found in cache ............ " + uri); // this line
```
4. Issue an IDP initiated SSO request to "Spring Security SAML SP" and notice the delay as well as the number of times the above line prints. The logout has similar problem.

I'm not sure if this needs to be integrated into the framework itself OR we should override DefaultMetadataCache to have a custom implementation. 

However, v1 had a separate metadata manager to auto refresh the metadata cache on the background. https://github.com/spring-projects/spring-security-saml/blob/rb1.0.4.RELEASE/core/src/main/java/org/springframework/security/saml/metadata/MetadataManager.java 

I think we will need a similar setup.

**Comment by fhanik** [comment]
Hi @gtiwari333, fast fail is an easy implementation, and we can cache the failure for configurable X amount of seconds. 

Just like the _background implementation_ it means that when the IDP is back up and running, you still have to wait for `X seconds` to pass by before it starts working again.

Both approaches have pros and cons. Of course, in both cases you're simply ignoring the elephant in the room. Why can't we expect a minimum service level of the IDP uptime in 2019? Meaning, are we implementing this feature for the 10% scenario or for the 0.0001% scenario?

I will implement this today. In the future, we love contributions and PRs, send them our way.

**Comment by fhanik** [comment]
@gtiwari333 Many thanks for the reports. Useful reports like this helps us improve the product.

Please review the [test cases](https://github.com/spring-projects/spring-security-saml/blob/ec70277767e5f1280c6ea471efc6f74b8efd9f8e/core/src/test/java/org/springframework/security/saml/spi/DefaultMetadataCacheTests.java#L40) for how the hit vs miss caches work
