### ISSUE TITLE
Provide a Handle to original SAML

### ISSUE THREAD

**Issue by adityagoel** [spring-projects/spring-security-saml#352]
Once the SAML validation is complete in SamlResponseAuthenticationFilter, there is no way to retrieve the original SAML sent by IDP. Propogating it out so it can be retrieved in Controller would help when using SAML Grant Type with Gateways(eg. WSO2) to exchange for an OAuth Token (ref: https://docs.wso2.com/display/AM210/SAML+Extension+Grant)

**Comment by fhanik** [comment]
Fixed. Thank you for the report.
