### ISSUE TITLE
Review SelectIdentityProviderFilter

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#355]
This is a review of SelectIdentityProviderFilter and support classes for it

* I think that SelectIdentityProviderFilter is doing too many things. It tries to allow selecting an IdP and allows initiating an authentication request. Instead, I think we should split this up into two different Filter's. This will better align with how the OAuth code works
  * The first would be named something like SamlLoginPageGeneratingFilter that can list out the IdP's and allow selecting a URL that performs the log in. Eventually this code will be merged into DefaultLoginPageGeneratingFilter
  * The second would be very similar to OAuth2AuthorizationRequestRedirectFilter. Perhaps it would be SamlAuthenticationRequestFilter? It can extract an identifier from the URL that it matches on and then it uses that to redirect or create an auto submitted POST form.
  * The AuthenticationEntryPoint can just redirect to the appropriate URL that is either a custom login page or a URL processed by the SamlAuthenticationRequestFilter above. 
* SelectIdentityProviderFilter doesn't really seem appropriate since it creates the SAML Authentication Request. Perhaps SamlAuthenticationRequestFilter?
* Rather than StandaloneHtmlWriter (which is public), please keep the logic private inside of the Filter that uses it. In general, we don't expose a class without an interface. Given Spring Security is not about writing HTML content we should not be creating abstractions for writing HTML. This means that all the components related to Html should be removed
* StandaloneHtmlWriter should not set cache headers. This is already done by Spring Security's headers support.
* StandaloneHtmlWriter has a setter method that returns StandaloneHtmlWriter. Spring Framework follows bean conventions which means it should be void
* There should be no need for SamlServiceProviderFilter which is implemented, but never used as an interface otherwise. Our abstraction is a Filter.
* The hierarchy seems like a bit much as SamlServiceProvider only uses two methods on the parents. It is best to have very specific classes that do specific things vs lumping a lot of functionality into a parent class.

**Comment by fhanik** [comment]
Thanks for the feedback

> * I think that SelectIdentityProviderFilter is doing too many things. It tries to allow selecting an IdP and allows initiating an authentication request. Instead, I think we should split this up into two different Filter's. This will better align with how the OAuth code works

It only does one thing. There may be a misunderstanding on what an authentication request is. An authentication request is a message from the `SP -> auth request -> IDP - auth response -> SP`
The [AuthenticationRequestFilter](https://github.com/spring-projects/spring-security-saml/blob/1164afee04592a58bb773518ca43ef8b89aa74d2/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/AuthenticationRequestFilter.java#L87) does that.

>   
>   * The first would be named something like SamlLoginPageGeneratingFilter that can list out the IdP's and allow selecting a URL that performs the log in. Eventually this code will be merged into DefaultLoginPageGeneratingFilter

The class has been renamed to [SamlLoginPageGeneratingFilter](https://github.com/spring-projects/spring-security-saml/blob/1164afee04592a58bb773518ca43ef8b89aa74d2/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L48)

The page lists out the IDPs that can be used for authentication.
An optional feature flag can be set to automatically redirect to the auth request filter if there is only one IDP.

>   * The second would be very similar to OAuth2AuthorizationRequestRedirectFilter. Perhaps it would be SamlAuthenticationRequestFilter? It can extract an identifier from the URL that it matches on and then it uses that to redirect or create an auto submitted POST form.

Already exists.  [AuthenticationRequestFilter](https://github.com/spring-projects/spring-security-saml/blob/1164afee04592a58bb773518ca43ef8b89aa74d2/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/AuthenticationRequestFilter.java#L87)

>   * The AuthenticationEntryPoint can just redirect to the appropriate URL that is either a custom login page or a URL processed by the SamlAuthenticationRequestFilter above.

If you want a different page, then just swap out the authentication entry point. Like using the LoginUrlAuthenticationEntryPoint.

> * SelectIdentityProviderFilter doesn't really seem appropriate since it creates the SAML Authentication Request. Perhaps SamlAuthenticationRequestFilter?

All it does is selecting an IDP to authenticate against. Filter name was ok, but nothing wrong with the generating page filter name either.

> * Rather than StandaloneHtmlWriter (which is public), please keep the logic private inside of the Filter that uses it. In general, we don't expose a class without an interface. Given Spring Security is not about writing HTML content we should not be creating abstractions for writing HTML. This means that all the components related to Html should be removed
> * StandaloneHtmlWriter should not set cache headers. This is already done by Spring Security's headers support.
> * StandaloneHtmlWriter has a setter method that returns StandaloneHtmlWriter. Spring Framework follows bean conventions which means it should be void

StandaloneHtmlWriter and supporting HTML classes have been folded in an made package private.
No headers are written

> * There should be no need for SamlServiceProviderFilter which is implemented, but never used as an interface otherwise. Our abstraction is a Filter.

Logic extracted into a utils class instead.

>* The hierarchy seems like a bit much as SamlServiceProvider only uses two methods on the

No class named `SamlServiceProvider`, but there is one called `HostedServiceProvider` - representing an SP. There is one called HostedIdentityProvider that represents IDP. During validation, it makes sense to extract the shared logic into a parent class.

All feedback incorporated. [develop-3.0 branch](https://github.com/spring-projects/spring-security-saml/tree/1164afee04592a58bb773518ca43ef8b89aa74d2)

**Comment by rwinch** [comment]
Let's start with another look at `SamlLoginPageGeneratingFilter`
* This will eventually get merged into `DefaultLoginPageGeneratingFilter`, so it's code should look very similar to it. 
* The only thing it should do is render links
* It should NOT perform any sort of redirects or automatic form posts
* The links that it renders should look something like `/saml2/authenticate/{registration-id}` to align with how `DefaultLoginPageGeneratingFilter` work with OAuth2 which uses `/oauth2/authorization/{registration-id}`
* We should not need any special types for this (if we do have them we will run into the danger of package tangles). You will notice that in `DefaultLoginPageGeneratingFilter` the only thing that is injected is a `Map<String,String> oauth2AuthenticationUrlToClientName` so we should have a similar mapping of link text to url. More concretely, that means `SamlLoginPageGeneratingFilter` should not need `SamlTransformer`, `ServiceProviderResolver`, `ServiceProviderValidator`, etc
* Please review the `DefaultLoginPageGeneratingFilter` and make `SamlLoginPageGeneratingFilter` align as much as you can with it. We also want to ensure that we have consistency here

**Comment by fhanik** [comment]
Will do

**Comment by fhanik** [comment]
Feedback incorporated

https://github.com/spring-projects/spring-security-saml/commit/4f6050397a02b5e0b1eb6fb6a5dc78112d858b95

**Comment by rwinch** [comment]
Continue reviewing of `SamlLoginPageGeneratingFilter`

* We should not need any Spring Security SAML APIs in this Filter. Please [remove them](https://github.com/spring-projects/spring-security-saml/blob/54e2f0bca8a1dc4c893357262ef08fd2c80d6c8f/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L29-L34). Instead inject a Map like is done in `DefaultLoginPageGeneratingFilter`. The Java Config will then initialize that `Map`.
* Currently the URL is http://localhost:8080/sample-sp/saml/sp/authenticate/simplesamlphp?idp=http%3A%2F%2Fsimplesaml-for-spring-saml.cfapps.io%2Fsaml2%2Fidp%2Fmetadata.php we should not include idp query parameter that has the URL. Instead, the URL should only have an identifier in it, so the AuthenticationRequestFilter can look up which IDP to look at. So the URL should look like `/saml2/authenticate/{registration-id}` or `http://localhost:8080/sample-sp/saml2/authenticate/simplesamlphp`
* Replace apache commons [StringEscapeUtils.escapeHtml](https://github.com/spring-projects/spring-security-saml/blob/54e2f0bca8a1dc4c893357262ef08fd2c80d6c8f/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L45) with [HtmlUtils](https://github.com/spring-projects/spring-security/blob/da0f9699298711706d1e6c38a20eb7d48a874832/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java#L326)
* No need to catch [IOException](https://github.com/spring-projects/spring-security-saml/blob/54e2f0bca8a1dc4c893357262ef08fd2c80d6c8f/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L94)...just let it propagate 
* Try to avoid large indentation blocks [like this](https://github.com/spring-projects/spring-security-saml/blob/54e2f0bca8a1dc4c893357262ef08fd2c80d6c8f/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L68-L98). Either move the logic to a method or invert the if statement and return i.e.

```java
if (!matcher.matches(request)) {
    filterChain.doFilter(request, response);
    return;
}
```

**Comment by fhanik** [comment]
Commit https://github.com/spring-projects/spring-security-saml/commit/bc4d1b9fde73a8a425294db4462e702c07b35dca

All but one feedback items incorporated. 

> We should not need any Spring Security SAML APIs in this Filter. Please remove them. Instead inject a Map like is done in DefaultLoginPageGeneratingFilter. The Java Config will then initialize that Map.

I read that you are proposing that all configuration is static.
What I would like is that configuration is resolved during request time. This caters to both multi tenant and non multi tenant scenarios. Creating static configuration first will make this much more difficult.

Given that this rewrite still caters to known usage scenarios that warrant at-request-time configuration resolution, it seems that we may choose to incorporate these features even at the MVP.

**Comment by rwinch** [comment]
**saml2**

* I think we should move to package `org.springframework.security.saml2` rather than [saml](https://github.com/spring-projects/spring-security-saml/tree/54e2f0bca8a1dc4c893357262ef08fd2c80d6c8f/service-provider/src/main/java/org/springframework/security/saml) or [saml.saml2](https://github.com/spring-projects/spring-security-saml/tree/0124a865126d09cb21b3cc34db835d2d9793d4e4/core/src/main/java/org/springframework/security/saml/saml2). First we want to be consistent across the SAML code. Second, this package aligns with our packaging across the framework (i.e. [oauth2](https://github.com/spring-projects/spring-security/tree/5.1.4.RELEASE/oauth2/oauth2-core/src/main/java/org/springframework/security/oauth2) and [hibernate5](https://github.com/spring-projects/spring-framework/tree/v5.1.5.RELEASE/spring-orm/src/main/java/org/springframework/orm/hibernate5))

**SamlLoginPageGeneratingFilter**

* [getAuthenticationRequestRedirectUrl](https://github.com/spring-projects/spring-security-saml/blob/bcdb9e783453f96e7299734cfcea2f27b2f79fbf/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L104) is unnecessary. There is no need to create a URL with scheme, host, and port is unnecessary.
* There is also no need to iterate over the URLs [two](https://github.com/spring-projects/spring-security-saml/blob/bcdb9e783453f96e7299734cfcea2f27b2f79fbf/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L66) [times](https://github.com/spring-projects/spring-security-saml/blob/bcdb9e783453f96e7299734cfcea2f27b2f79fbf/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L88), nor to create another [Map](https://github.com/spring-projects/spring-security-saml/blob/bcdb9e783453f96e7299734cfcea2f27b2f79fbf/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/web/filters/SamlLoginPageGeneratingFilter.java#L65). Instead just use the context root as you are writing out the values as is done in the [DefaultLoginPageGeneratingFilter](https://github.com/spring-projects/spring-security/blob/5.1.4.RELEASE/web/src/main/java/org/springframework/security/web/authentication/ui/DefaultLoginPageGeneratingFilter.java#L282)

**DynamicSelectIdentityProviderFilter**

* Go ahead and remove `DynamicSelectIdentityProviderFilter` as it suggests in the comments. If you need it, you can get it in the commit history.

**AuthenticationRequestFilter**

* Rename to `Saml2AuthenticationRequestFilter`
* Remove long indentation. Either invert the if statement with a return 

```java
if (getMatcher().matches(request)) {
    filterChain.doFilter(request, response);
    return;
}
try {
    ...
```
or move the indentation into a separate method.
* I'd like to see `AuthenticationRequestFilter` have a single responsibility (rendering the redirect or automated POST). It seems like a good way to do this would be to have a `Saml2AuthenticationRequestResolver.resolve(HttpServletRequest)` interface. The `Filter` would let the resolver determine the model and then use that to render the page.

**Comment by fhanik** [comment]
Review ready at [commit 372f7bb6a](https://github.com/spring-projects/spring-security-saml/tree/584be2827bb1d19df53c8f7a21eed7c372f7bb6a)

1. Package has been renamed to `org.springframework.security.saml2`
2. SamlLoginPageGeneratingFilter generates domain relative URLs
3. DynamicSelectIdentityProviderFilter has been removed
4. [AuthenticationRequestFilter](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L40-L66) has been improved

**Comment by rwinch** [comment]
**General**

* In general domain objects (i.e. `AuthenticationRequest`) should start with `Saml2` to align with the oauth2 support. Changing `AuthentiationRequest` to `Saml2AuthenticationRequest` also better aligns with the name of `Saml2AuthenticationRequestFilter` and `Saml2AuthenticationResolver`
* Find `Saml` and replace with `Saml2` (i.e. `SamlServiceProviderStarterApplication`)
* Separate the domain objects from functionality (keep them simple POJOs). For example, `AuthenticationRequest` should not have any methods related to XML on it. This allows the same domain object to be rendered in multiple different ways. It also simplifies the domain objects significantly. Right now it is confusing that there is a property named originalXML from the perspective of the `Saml2AuthenticationRequestFilter` which does not need it.

**HTML**
* The AbstractHtmlContent only contains a single method to get the HTML and each subclass is only used in a single location. Remove AbstractHtmlContent, ErrorHtml, PostBindingHtml, and StandaloneHtmlWriter in favor of just using a String in a private method. 

**Saml2AuthenticationRequestFilter**

* It is unlikely that we need the `Endpoint` [as an argument](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L69) since it comes from the `AuthentivationRequest`
* Remove [sendAuthenticationRequest](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L68) and [encode](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/authentication/Saml2AuthenticationRequestResolver.java#L24) in favor of adding the model attributes to `AuthenticationRequest` object. For example `AuthenticationRequest` might have a `authenticationRequestUri` attribute which is used directly for redirecting. This allows the existing `Saml2AuthenticationRequestResolver` interface to be used to customize the URL
* Use a [RedirectStrategy](https://github.com/spring-projects/spring-security/blob/3c95c0810658d969216c7888ee4a14c3e7027a66/web/src/main/java/org/springframework/security/web/RedirectStrategy.java) for [sending the redirect](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L81)

**Saml2AuthenticationRequestResolver**

* Remove [`<HttpRequest>` type parameter](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/authentication/Saml2AuthenticationRequestResolver.java#L22) and prefer to use `HttpServletRequest` directly. This is more consistent with existing Spring Security APIs.
* Change `Saml2WebAuthenticationRequestResolver` to `Saml2AuthenticationRequestResolver`

**Comment by fhanik** [comment]
**General**

> * In general domain objects (i.e. `AuthenticationRequest`) should start with `Saml2` to align with the oauth2 support. Changing `AuthentiationRequest` to `Saml2AuthenticationRequest` also better aligns with the name of `Saml2AuthenticationRequestFilter` and `Saml2AuthenticationResolver`
> * Find `Saml` and replace with `Saml2` (i.e. `SamlServiceProviderStarterApplication`)

Completed

> * Separate the domain objects from functionality (keep them simple POJOs). For example, `AuthenticationRequest` should not have any methods related to XML on it. This allows the same domain object to be rendered in multiple different ways. It also simplifies the domain objects significantly. Right now it is confusing that there is a property named originalXML from the perspective of the `Saml2AuthenticationRequestFilter` which does not need it.

These objects will never be rendered into and from anything but XML. The accessor `getOriginalXML` allows a developer to retrieve the original declaration of the object.
It's an important feature when the XML contains custom tags that go beyond the spec and are ignored by the mapper.
Example: https://github.com/spring-projects/spring-security-saml/issues/352

the accessor could be renamed to `getOriginalDataRepresentation`. I'm open to ideas on how this data would be propagated if it wasn't inside the object (given it can be needed for almost any object)

**HTML**

>* The AbstractHtmlContent only contains a single method to get the HTML and each subclass is only used in a single location. Remove AbstractHtmlContent, ErrorHtml, PostBindingHtml, and StandaloneHtmlWriter in favor of just using a String in a private method. 

Completed. 


**Saml2AuthenticationRequestFilter**

> * It is unlikely that we need the `Endpoint` [as an argument](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L69) since it comes from the `AuthentivationRequest`

Completed. 

> * Remove [sendAuthenticationRequest](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L68) and [encode](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/authentication/Saml2AuthenticationRequestResolver.java#L24) in favor of adding the model attributes to `AuthenticationRequest` object. 

Need more info or an example. I will review the OAuth code base to see if I can figure it out on my own.

> For example `AuthenticationRequest` might have a `authenticationRequestUri` attribute which is used directly for redirecting. This allows the existing `Saml2AuthenticationRequestResolver` interface to be used to customize the URL

This is already achieved. `AuthenticationRequest.setDestination` allows the Saml2AuthenticationRequestResolver to customize the destination.
_authenticationRequestUri_ is not the correct data type here. It would be an endpoint, since an endpoint defines the destination and delivery mechanism, both set by the resolver.

> * Use a [RedirectStrategy](https://github.com/spring-projects/spring-security/blob/3c95c0810658d969216c7888ee4a14c3e7027a66/web/src/main/java/org/springframework/security/web/RedirectStrategy.java) for [sending the redirect](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/web/filters/Saml2AuthenticationRequestFilter.java#L81)

Completed.

**Saml2AuthenticationRequestResolver**

> * Remove [`<HttpRequest>` type parameter](https://github.com/spring-projects/spring-security-saml/blob/584be2827bb1d19df53c8f7a21eed7c372f7bb6a/service-provider/src/main/java/org/springframework/security/saml2/serviceprovider/authentication/Saml2AuthenticationRequestResolver.java#L22) and prefer to use `HttpServletRequest` directly. This is more consistent with existing Spring Security APIs.

Completed.

> * Change `Saml2WebAuthenticationRequestResolver` to `Saml2AuthenticationRequestResolver`

Completed.

**Comment by fhanik** [comment]
Closing in favor of a new issue being opened. The filter in the title no longer exists.
