### ISSUE TITLE
SelectIdentityProviderFilter  has an incomplete message in the log message

### ISSUE THREAD

**Issue by wizdata** [spring-projects/spring-security-saml#357]
SelectIdentityProviderFilter  line 91-96

						logger.debug(format(
							"Unable to retrieve metadata for provider:%s with message:",
							p.getMetadata(),
							x.getMessage()
							)
						);
Should be:
						logger.debug(format(
							"Unable to retrieve metadata for provider:%s with message:%s",
							p.getMetadata(),
							x.getMessage()
							)
						);

**Comment by fhanik** [comment]
@wizdata Thanks for the report. Fixed via https://github.com/spring-projects/spring-security-saml/commit/161196da8ced26d7300b11a7f17cdf476fef7882
