### ISSUE TITLE
RestTemplate should be built from RestTemplateBuilder

### ISSUE THREAD

**Issue by wizdata** [spring-projects/spring-security-saml#358]
package org.springframework.security.saml.provider.config;
...
	public RestOperations get(boolean skipSslValidation) {
		return new RestTemplate(createRequestFactory(skipSslValidation));
	}

class ProxyCustomizer implements RestTemplateCustomizer won't work since RestOperations is hard coded

**Comment by wizdata** [comment]
/** Code Change --- Expose ValidatingNetwork and NonValidatingNetwork and make them cutomizable   SamlMetadataCache */

package org.springframework.security.saml.spi;
    public class DefaultMetadataCache implements SamlMetadataCache
    ...
       	public RestOperations getValidatingNetwork() {
		return validatingNetwork;
	}

	public RestOperations getNonValidatingNetwork() {
		return nonValidatingNetwork;
	}

//Example to configure bean for  Customization
@Configuration
public class BeanConfig extends SamlServiceProviderServerBeanConfiguration {
@Bean
	public SamlMetadataCache SamlMetadataCache(RestTemplateBuilder builder, SamlMetadataCache samlMetadataCache) {
		builder.configure((RestTemplate) ((DefaultMetadataCache) samlMetadataCache).getNonValidatingNetwork());
		builder.configure((RestTemplate) ((DefaultMetadataCache) samlMetadataCache).getValidatingNetwork());
		return  samlMetadataCache;
	}

**Comment by fhanik** [comment]
hi @wizdata,

In our [milestone releases (2.0.x) the beans are there](
https://github.com/spring-projects/spring-security-saml/blob/d3faddb21526a1dccbe9adcdd879a95620049d61/core/src/main/java/org/springframework/security/saml/provider/config/AbstractSamlServerBeanConfiguration.java?ts=4#L113-L121)

For our rewrite, it has been deemed better to start coarse grained, and you'd override the [metadata resolver](https://github.com/spring-projects/spring-security-saml/blob/11556eb60dbc947556fde89fda3da0d3b2d5068c/service-provider/src/main/java/org/springframework/security/saml/serviceprovider/bean/SamlServiceProviderBeans.java#L53-L56) or you just call `DefaultServiceProviderMetadataResolver.setCache` yourself.

We're starting with coarse grained extension model on the rewrite and may loosen it up where needed. Right now, the goal is to work towards an API that aligns well with Spring Security, so developers have a similar experience with SAML as they do with OAuth2/OIDC for example.
