### ISSUE TITLE
Allow configuration of preferred Binding on AuthenticationRequest

### ISSUE THREAD

**Issue by mreines** [spring-projects/spring-security-saml#359]
When creating a AuthenticationRequest in the HostedServiceProviderService, the preferred SingleSignOn endpoint is hardwired to Binding.REDIRECT. Some IdP's (Azure in particular) don't support this and this should probably be set from the IdP metadata if it exists. 

I would propose adding a preferred index in the ExternalIdentityProviderConfiguration that would allow the configuration to drive the selected Binding.

The scenario with Azure is that they support Http-Post only but Http-Redirect is the first binding in the list in the metadata. 
EX:
```
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://login.microsoftonline.com/061e3edf-59f6-48b3-a176-f93c936cced0/saml2"/>
<SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://login.microsoftonline.com/061e3edf-59f6-48b3-a176-f93c936cced0/saml2"/>
```

So we always end up with Http-Redirect, however, this is **NOT** supported for Response binding. This seems weird, but MS is huge in the Identity space and I feel this provision is probably worth working around.

https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/provider/service/HostedServiceProviderService.java#L128

I am also willing to work this issue - if you agree to the behaviour change. Would love to be accepted as a contributor to this repo as well.

Sceenshot from MS when it received AuthnRequest.... 
<img width="642" alt="screen shot 2019-02-13 at 7 09 02 am" src="https://user-images.githubusercontent.com/1219269/52717476-6c2f9600-2f5e-11e9-81a0-5657d0c397b4.png">

**Comment by fhanik** [comment]
hi @mreines, thank you so much for the detailed report.

The intention was there, but I can see it's not working correctly.

The [`AbstractHostedProviderService.getPreferredEndpoint`](https://github.com/spring-projects/spring-security-saml/blob/f5e82499ede141113a5e7cf64298ce635b6405db/core/src/main/java/org/springframework/security/saml/provider/AbstractHostedProviderService.java#L327-L368) method should work as follows

1. Pick the default, if IDP the metadata has one binding that has `isDefault="true"`
2. Pick the configured one (this functionality is lacking, the index is always set to 0)
3. If we don't have a default, nor a configured one, see if the preferred is available (redirect)
4. If we still haven't found a _preferred binding_, pick the first one in the list.

Feel free to submit a Pull Request. You should be able to write multiple [test cases](https://github.com/spring-projects/spring-security-saml/blob/a365c97abfcce56424ea9f2b1191bc98edb3427b/samples/boot/simple-service-provider/src/test/java/org/springframework/security/samples/SimpleServiceProviderBootTest.java#L202-L208) that modifies the configuration for each scenario.

```
	@Test
	public void authnRequestWithConfiguredNameId() throws Exception {
		config.getServiceProvider().getProviders().stream()
			.forEach(p -> p.setNameId(NameId.PERSISTENT));
		AuthenticationRequest authn = getAuthenticationRequest();
		assertThat(authn.getNameIdPolicy().getFormat(), equalTo(NameId.PERSISTENT));
	}
```

**Comment by mreines** [comment]
Great, I understand the intent a little better now. Reading through the code, it seems it might be a better idea to add the ability to set the preferred Binding, rather than index (although setting by index might be nice later, I think the Binding is probably more important).
This would involve adding a property to the configuration [ExternalProviderConfiguration](https://github.com/spring-projects/spring-security-saml/blob/f5e82499ede141113a5e7cf64298ce635b6405db/core/src/main/java/org/springframework/security/saml/provider/config/ExternalProviderConfiguration.java), something like 'defaultBinding'.
Would you agree to this approach?

**Comment by fhanik** [comment]
I agree. Spring likes descriptive names, so something like `authenticationRequestBinding` may work.
(since there probably be a way to configure preferred logoutBinding)

**Comment by fhanik** [comment]
@mreines 
Hi Matt, 

If you want some ideas, I added a commit to the [_rewrite MVP branch_ (link)](https://github.com/spring-projects/spring-security-saml/commit/a1109e8c0107294909ba47282673d21e30cfe79b)

Your PR should go to the `develop` branch. Where you pointed out the flaw.

> This is the branch that will be used when it's ready to merge the product into Spring Security core. 
> It's a rewrite from our milestone releases. 
> I used null as the default binding.

**Comment by fhanik** [comment]
@mreines Thank you for your contribution. Keep them coming.
I added [one commit](https://github.com/spring-projects/spring-security-saml/commit/ca29a44d4777425e9553d8e97ef960ef1b95d935) on top of yours that does an integration test (to ensure that the correct binding is actually used)

**Comment by mreines** [comment]
@fhanik Your welcome, will stay involved as much as I can. Would love to see this rolled into spring security. 
Any chance we can get to Milestone 25 sometime soon? We're needing these changes for the HTTP-POST stuff as soon as we can! Thanks!
