### ISSUE TITLE
Need milestone release with preferred binding feature

### ISSUE THREAD

**Issue by mreines** [spring-projects/spring-security-saml#365]
Hoping a Milestone release off the develop branch can be pushed out sometime soon. We're looking to move forward with utilization of this library and that is definitely something we require to keep moving. Thank you!

**Comment by fhanik** [comment]
Coming up.

**Comment by fhanik** [comment]
Here it is: https://github.com/spring-projects/spring-security-saml/releases/tag/2.0.0.M25

**Comment by mreines** [comment]
Thank you Filip!
