### ISSUE TITLE
Could anyone tell me how to set custom AssertionConsumerServiceURL？

### ISSUE THREAD

**Issue by BlueSky5300** [spring-projects/spring-security-saml#367]
Could anyone tell me how to set custom AssertionConsumerServiceURL？
I can not find anywhere can do that.
Thanks.

**Comment by fhanik** [comment]
@BlueSky5300 
What version are you attempting to use?

When wanting to change the ACS URL, it will have to happen in two places:

1. The metadata generated - so that the other party can read the new URL
2. The filter that hosts the endpoint will have to respond to the new URL

**Comment by BlueSky5300** [comment]
spring-security-saml2-core [1.0.3.RELEASE]
spring-boot-starter-security [2.1.1.RELEASE]

**Comment by BlueSky5300** [comment]
One more question, IS the NameIdPolicy attribute necessary in SAML request? My SAML request doesn't have NameIdPolicy attribute and I always get InvalidNameIdPolicy message from SAML response.

**Comment by fhanik** [comment]
```
AllowCreate [Optional]
A Boolean value used to indicate whether the identity provider is allowed, in the course of fulfilling the
request, to create a new identifier to represent the principal. Defaults to "false". When "false", the
requester constrains the identity provider to only issue an assertion to it if an acceptable identifier for
the principal has already been established. Note that this does not prevent the identity provider from
creating such identifiers outside the context of this specific request (for example, in advance for a
large number of principals)
```

http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf
