### ISSUE TITLE
digest: SHA-256=... not in header

### ISSUE THREAD

**Issue by wizdata** [spring-projects/spring-security-saml#390]
authnRequest not signed

**Comment by wizdata** [comment]
This is for V.2

**Comment by wizdata** [comment]
I can use RestTemplateCustomizer to add headers. Is that the right way to do it?

**Comment by wizdata** [comment]
Want confirmation

**Comment by fhanik** [comment]
hi @wizdata 

V2 doesn't carry signature in headers (or parameters). It only uses embedded signatures.
Does that answer your question?

**Comment by wizdata** [comment]
I mean code in develop branch. and for redirect authentication. Should signature in the query string?

**Comment by fhanik** [comment]
@wizdata I'm not sure what you mean. Can you spell out the actual question and describe what you are trying to do?
