### ISSUE TITLE
gretty 2.2.0 : code 502 Bad Gateway

### ISSUE THREAD

**Issue by bigalnz** [spring-projects/spring-security-saml#396]
Hi

When I try to execute : ./gradlew :spring-security-saml-samples/boot/simple-service-provider:bootRun &

I get :  

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'spring-security-saml2'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve gradle.plugin.org.gretty:gretty:2.2.0.
     Required by:
         project : > io.spring.gradle:spring-build-conventions:0.0.23.RELEASE
      > Could not resolve gradle.plugin.org.gretty:gretty:2.2.0.
         > Could not get resource 'https://jcenter.bintray.com/gradle/plugin/org/gretty/gretty/2.2.0/gretty-2.2.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/gradle/plugin/org/gretty/gretty/2.2.0/gretty-2.2.0.pom'. Received status code 502 from server: Bad Gateway

I am in Intellij.

**Comment by fhanik** [comment]
Closing. Works for us. Let us know if you continue to experience this.

**Comment by zyhalj** [comment]
I can run gradlew :spring-security-saml-samples/boot/simple-service-provider:bootRun &
But I get below error.  I'm trying on spring-security-saml-2.0.0.M27
...
FAILURE: Build failed with an exception.

* What went wrong:
Task 'bootRun' not found in project ':spring-security-saml2-samples/boot/simple-service-provider'.
