### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by vis-dev** [spring-projects/spring-security-saml#413]
Hi, I'm trying to use the latest milestone release (M26), I can't find a documentation for the same, after spending some time going through the example simple-service-provider, I can understand that the configuration is done through application.yml file in spring boot, how can I integrate it in a non Spring boot (but Spring) application and whether this version supports the XML based configuration ? I can't see applicationContext.xml and when copied from other version, it's not supported (missing beans). Any help on pointing to the right documentation will be great. Thanks

BTW, I'm trying to integrate the latest 2.X version of this library in a legacy Struts1 + Spring based App. (non Spring boot)

**Comment by fhanik** [comment]
Hi @vis-dev 

All you have to do is provide a `@Bean` of type `SamlServerConfiguration`

    @Bean 
    public SamlServerConfiguration samlServerConfiguration() {
        //return the stuff created by application.yml here
    }

If you review a sample, you can see that the `application.yml` stuff really only does 

```
@ConfigurationProperties(prefix = "spring.security.saml2")
@Configuration
public class AppConfig extends SamlServerConfiguration {
}
```
