### ISSUE TITLE
Current release mess

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-security-saml#415]
According to [the homepage](https://projects.spring.io/spring-security-saml/) the current GA is 1.0.6.RELEASE.
However, the dependency [`ca.juliusdavies:not-yet-commons-ssl:jar:0.3.17`](https://mvnrepository.com/artifact/ca.juliusdavies/not-yet-commons-ssl/0.3.17) is only in the Mulesoft repo, not Central.
The documentation links are also to 1.x, so currently show 1.0.10-SNAPSHOT instead of the actual versions.

According to [the documentation](https://docs.spring.io/spring-security-saml/docs/current/reference/html/) the current GA is actually 1.0.9.RELEASE.
However, the dependency [`org.opensaml:opensaml:2.6.6`](https://mvnrepository.com/artifact/org.opensaml/opensaml/2.6.6) is only in the Alfresco and Shibboleth repos, not Central.

**Comment by fhanik** [comment]
The 1.0.x branch continues to take in PRs from the community, development is limited to that.
We don't foresee any major documentation changes.
Thanks for reporting the projects.spring.io deficiency. I have fixed that.
