### ISSUE TITLE
Potential XSS Vulnerability

### ISSUE THREAD

**Issue by chenry** [spring-projects/spring-security-saml#417]
Good morning,

I am doing some investigation on an XSS vulnerability in our application that uses spring-security-saml.  I think that I may have discovered a potential problem in the IdpInitiatedLoginFilter for the POST Binding.  

It appears as though the **RelayState** is being sent back to the client unencoded.  As I understand it, this makes it possible for someone to put in malicious code for the RelayState and have that code executed on the client browser.

For now, I am going to try to resolve this issue through the use of a custom velocity template for rending the login page.  

Thanks

**Comment by fhanik** [comment]
hi @chenry 

Thank you for the report! I have fixed this. and will be issuing a new milestone today.

In the [rewrite](https://github.com/spring-projects/spring-security-saml/blob/d5bff5dda96d33d3df5637f864c7ed18c469c289/service-provider/web/src/main/java/org/springframework/security/saml2/serviceprovider/web/binding/DefaultSaml2HttpMessageResponder.java#L129-L134), it's always encoded in the HTML

In the future, please report potential security issues via security@pivotal.io
