### ISSUE TITLE
Add hook in SamlAuthenticationRequestFilter for enhancing AuthenticationRequest

### ISSUE THREAD

**Issue by oharsta** [spring-projects/spring-security-saml#424]
In the `develop` branch the `SamlAuthenticationRequestFilter` is responsible for initiating the SAML login process by sending the `AuthenticationRequest` to the selected Identity Provider. 

Subclasses that want to enhance the `AuthenticationRequest` before sending it to the IdP currently have no hook to do so.

**Comment by oharsta** [comment]
Implemented in https://github.com/spring-projects/spring-security-saml/pull/425

**Comment by fhanik** [comment]
Closed via: https://github.com/spring-projects/spring-security-saml/commit/20301bf79514aa74743aaec47c4c1df20d8537d8
