### ISSUE TITLE
Update version on site in README

### ISSUE THREAD

**Issue by samcdavid** [spring-projects/spring-security-saml#463]
The [project site](https://projects.spring.io/spring-security-saml/) says that `1.0.9.RELEASE` is the current version. However, following the sample app, it looks like `2.0.0.M31` is the latest release.

Which is correct? If `1.0.9.RELEASE` is no longer the current stable version, will you update the [project site](https://projects.spring.io/spring-security-saml/).

Thanks.

**Comment by jzheaux** [comment]
@samcdavid thanks for reaching out. The project site currently shows 1.0.10.RELEASE as the latest GA release of `spring-security-saml`, which is correct. (This may have been updated since you last checked.)

**Comment by jzheaux** [comment]
Note that `2.0.0.M31` is a milestone release and, as such, isn't considered the latest GA release. 

Additionally, the `2.x` line was moved into [Spring Security](https://github.com/spring-projects/spring-security), so please follow that project for further enhancements.
