### ISSUE TITLE
1.0.10.RELEASE?

### ISSUE THREAD

**Issue by OrangeDog** [spring-projects/spring-security-saml#465]
There's a tag for [1.0.10.RELEASE](https://github.com/spring-projects/spring-security-saml/releases/tag/1.0.10.RELEASE), but it doesn't look like it was actually released to [Maven Central](https://repo1.maven.org/maven2/org/springframework/security/extensions/spring-security-saml2-core/).

**Comment by fhanik** [comment]
https://search.maven.org/artifact/org.springframework.security.extensions/spring-security-saml2-core/1.0.10.RELEASE/jar

**Comment by OrangeDog** [comment]
Thanks. There's no GitHub release either: https://github.com/spring-projects/spring-security-saml/releases

**Comment by fhanik** [comment]
https://github.com/spring-projects/spring-security-saml/releases/tag/1.0.10.RELEASE

**Comment by OrangeDog** [comment]
And here: https://projects.spring.io/spring-security-saml/
