### ISSUE TITLE
SAMLUtil.isDateTimeSkewValid having int overflow 

### ISSUE THREAD

**Issue by wojciech-piotrowiak** [spring-projects/spring-security-saml#478]
Recently noticed such error in our app:

> Caused by: java.lang.IllegalArgumentException: The end instant must be greater than the start instant
> 	at org.joda.time.base.AbstractInterval.checkInterval(AbstractInterval.java:63)
> 	at org.joda.time.base.BaseInterval.<init>(BaseInterval.java:94)
> 	at org.joda.time.Interval.<init>(Interval.java:199)
> 	at org.springframework.security.saml.util.SAMLUtil.isDateTimeSkewValid(SAMLUtil.java:531)
> 	at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAuthenticationStatement(WebSSOProfileConsumerImpl.java:573)
> 	at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAssertion(WebSSOProfileConsumerImpl.java:344)
> 	at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:250)

After debugging, realized that it happen when our application having maximum timeout available, which is Integer.MAX_VALUE. It is possible, because WebSSOProfileConsumerImpl accept long as maxAuthenticationAge param. So default skewInSec plus maximum forwardInterval will not fit into integer and it makes a problem for Interval class, as below:

<img width="1680" alt="Screen Shot 2020-05-04 at 3 31 15 PM" src="https://user-images.githubusercontent.com/208200/81013615-bd75bf00-8e5b-11ea-9683-f806a848ff52.png">

Used latest spring-security-saml2-core:1.0.10.RELEASE, previously used 1.0.3 and that version accepted Integer.MAX_VALUE as timeout.

**Comment by wojciech-piotrowiak** [comment]
@rwinch @jzheaux 
Is this defect have a chance to be fixed and released?
If yes, can I try and open pull request ?

**Comment by jzheaux** [comment]
Yes, @wojciech-piotrowiak, thank you for offering! A pull request would be welcome.

**Comment by wojciech-piotrowiak** [comment]
@rwinch @jzheaux 
PR opened: https://github.com/spring-projects/spring-security-saml/pull/481
