### ISSUE TITLE
2.0.0.M31   how to use userdetailservers

### ISSUE THREAD

**Issue by shuweicn** [spring-projects/spring-security-saml#479]
How to verify the logged in user, I want custom login process and set user in to local database.
if user not in local database limit user login, where is login hook.

**Comment by shuweicn** [comment]
where SAMLUserDetailsService in 2.0.0M31

**Comment by rwinch** [comment]
This project is in maintenance mode. The milestones never made it to GA because we merged our efforts into Spring Security proper. I'd switch to Spring Security SAML support https://docs.spring.io/spring-security/site/docs/5.3.x/reference/html5/#servlet-saml2

**Comment by shuweicn** [comment]
Thank you rwinch
