### ISSUE TITLE
Can't find replacement for SAMLCredential & SAMLUserdetailsservice in version 2

### ISSUE THREAD

**Issue by ash213** [spring-projects/spring-security-saml#480]
We are trying to upgrade opensaml to version 3 as a part of which we also need to upgrade spring security saml to 2.0.0.M31, as the earlier versions work with opensaml 2.6.4. We can't find replacement for below classes in the code, these classes were removed during a cleanup but can't find any details other than this. Any help is appreciated.

**Comment by rwinch** [comment]
Please use Spring Security's SAML support instead since the 2.x branch never made it to GA (it went into Spring Security proper instead). Please see https://docs.spring.io/spring-security/site/docs/5.3.x/reference/html5/#servlet-saml2
