### ISSUE TITLE
Could not verify the provided CSRF token because your session was not found.

### ISSUE THREAD

**Issue by sundarvc** [spring-projects/spring-security-saml#501]
Hi ,

I am new to Spring Security and when I run the sample app, after redirection I get this error in the sample app.
Any thoughts? 

Thanks,
Sundar

**Comment by jzheaux** [comment]
Hi, @sundarvc. When you say "this error", I don't see anything in the ticket. Could you elaborate?

**Comment by sundarvc** [comment]
Hi Josh,

Thanks for responding to my question.

After I am authenticated, I see this error in my browser (url: http://localhost:8080/spring-security-saml2-sample/saml/SSO)

**HTTP Status 403 – Forbidden
Type Status Report
Message Could not verify the provided CSRF token because your session was not found.
Description The server understood the request but refuses to authorize it.**

For this to work I had to disable csrf by placing  <security:csrf disabled="true"/> in securityContext.xml. Any other suggestions ?

Thanks,
Sundar

**Comment by bedirachit** [comment]
Yeah, I have the same issue.

**Comment by jzheaux** [comment]
Thanks for the report, @sundarvc and @bedirachit. I've posted a change to the sample, please let me know if that repairs the issue.
