### ISSUE TITLE
Depenedencies can not be loaded since repo.spring.io got restricted

### ISSUE THREAD

**Issue by thorbolo** [spring-projects/spring-security-saml#508]
Tried building the project but the depenedencies can not be loaded from repo.spring.io since that got some permission changes.

See: https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020

Resulting in:

 Could not resolve net.sf.docbook:docbook-xsl-saxon:1.0.0.
     Required by:
         project : > io.spring.gradle:docbook-reference-plugin:0.3.1
      > Could not resolve net.sf.docbook:docbook-xsl-saxon:1.0.0.
         > Could not get resource 'https://repo.spring.io/plugins-release/net/sf/docbook/docbook-xsl-saxon/1.0.0/docbook-xsl-saxon-1.0.0.pom'.
            > Could not GET 'https://repo.spring.io/plugins-release/net/sf/docbook/docbook-xsl-saxon/1.0.0/docbook-xsl-saxon-1.0.0.pom'. Received status code 401 from server: Unauthorized

during the build process.

**Comment by jzheaux** [comment]
Thanks for the report, @thorbolo, I've updated the build to use the appropriate repositories.
