### ISSUE TITLE
login sometimes is only possible at the second click

### ISSUE THREAD

**Issue by vanessa-siemon-EB** [spring-projects/spring-security-saml#520]
You need to click twice on login until you receive the correct answer, The first answer is 401.

The case occurs, for example, after database initialization or when you do nothing in the session for a long time (let the page stand still).
While debugging we noticed that in the session the attribute "_springSamlStorageKey" is NULL. As a result, the WebSSOProfileConsumer breaks with NULL when it tries to read from the response "inRespsoneTo" from the messageStorage.

Hint: we integrated SSO in SAP Commerce as login against our company specific SAP IDP.

**Comment by jzheaux** [comment]
Hi, @vanessa-siemon-EB! This project has reached its [End-of-Life](https://spring.io/blog/2020/09/22/spring-security-saml-extensions-1-x-eol-on-october-6-2021).

If you are able, migrating to [Spring Security](https://docs.spring.io/spring-security/reference/5.6.0/index.html) is recommended.

For your question, I'd recommend posting to [StackOverflow](https://stackoverflow.com) for help in adjusting your application. You are welcome to link to the SO question here for additional visibility.
