### ISSUE TITLE
SES-62: Support for NameIDPolicy in WebSSO profile

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security-saml#65]
[Vladimir Schäfer](https://jira.spring.io/secure/ViewProfile.jspa?name=vsch) (Migrated from [SES-62](https://jira.spring.io/browse/SES-62)) said:

It should be possible to specify required nameID policy in AuthnRequest.

**Comment by wizdata** [comment]
How to set NameIDPolicy in saml2
