### ISSUE TITLE
SES-73: Major security issue - Invalid signatures on SAML assertions not detected

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-security-saml#72]
[William Miller](https://jira.spring.io/secure/ViewProfile.jspa?name=anon4321) (Migrated from [SES-73](https://jira.spring.io/browse/SES-73)) said:

Invalid signatures on SAML assertions DO NOT prevent the assertion from being accepted.    This is a major security issue.   This may also affect other signature validations on other SAML message types.

The code assumes that the signature trust engine will throw an exception when the signature is invalid when the semantics of the validate function states that false will be returned.

The return value is NOT being checked.

Line 237 in spring-security-saml/src/org/springframework/security/saml/websso/AbstractProfileBase.java must be changed to something such as:
        if (! trustEngine.validate(signature, criteriaSet)) {
            throw new ValidationException("Signature is not trusted or invalid");
        }
or the return value from validate must be returned from the  verifySignature funciton and checked by the caller.

**Comment by spring-issuemaster** [comment]
This issue duplicates #57
